services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: docker/dev-environments-default:stable-1
    init: true
    volumes:
    - type: volume
      source: volume-kindtek-yubi-net-sdk 
      target: /var/run/docker.sock

volumes:
  - volume-kindtek-yubi-net-sdk


