services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: docker/kasmweb/core-ubuntu-bionic:1.11.0
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock

