version: "3.8"
# name: yubico-net-sdk-distracted_rubin
services:
  yesdk-docserver:
    init: true
    ports:
    - "8080:8080"
    build: /com.docker.devenvironments.code/Yubico.NativShims/docker/Ubuntu
#  push_service1:
#    build: .
#    ports:
#    - "443:443"
#    image: kindtek/sdb_yub_k:latest  ## goes to your repository on Docker Hub
  web:
    entrypoint:
    - sleep
    - infinity
    image: docker/dev-environments-default:stable-1
    init: true
    volumes:
    - type: volume
      source: volume-docker-sock
      target: /var/run/docker.sock
      
  yubi:
    command:
    - infinity
    entrypoint:
    - sleep
    image: docker/dev-environments-default:stable-1
    init: true
    labels:
      com.docker.devenvironments: "true"
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.container: "true"
      com.docker.devenvironments.name: yubico-net-sdk-distracted_rubin
    networks:
      default: null
    stop_signal: SIGKILL
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
    - type: volume
      source: volume-yubico-net-sdk-distracted_rubin
      target: /com.docker.devenvironments.code
    - type: volume
      source: vsCodeServerVolume-yubico-net-sdk-distracted_rubin-app
      target: /home/vscode
  sol:
    command:
    - "apt-get update -qq && apt-get install -yq wget"
    entrypoint:
    - "/usr/bin/solana-run.sh"
    image: solanalabs/solana:stable
    ports:
    - "8899:8899"
    init: true
    labels:
      com.docker.devenvironments: "true"
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.container: "true"
      com.docker.devenvironments.name: yubico-net-sdk-distracted_rubin
    networks:
      default: null
    stop_signal: SIGKILL
    volumes:
    - type: volume
      source: volume-yubico-net-sdk-distracted_rubin-sol
      target: /usr/bin
  app:
    depends_on:
    - "sol"
    - "yubi"
    command:
    - infinity
    entrypoint:
    - sleep
    image: docker/dev-environments-default:stable-1
    init: true
    labels:
      com.docker.devenvironments: "true"
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.container: "true"
      com.docker.devenvironments.name: yubico-net-sdk-distracted_rubin
    networks:
      default: null
    stop_signal: SIGKILL
    volumes_from:
    - sol
    - yubi
networks:
  default:
    name: yubico-net-sdk-distracted_rubin_default
volumes:
  volume-yubico-net-sdk-distracted_rubin:
    name: volume-yubico-net-sdk-distracted_rubin
    #external: true
  vsCodeServerVolume-yubico-net-sdk-distracted_rubin-app:
    name: vsCodeServerVolume-yubico-net-sdk-distracted_rubin-app
    #external: true
  volume-yubico-net-sdk-distracted_rubin-sol:
    name: volume-yubico-net-sdk-distracted_rubin-sol
    #external: true
  volume-docker-sock:
    name: volume-docker-sock
    #external: true



