{
    global:
        Native_BN_bin2bn;
        Native_BN_bn2bin;
        Native_BN_num_bytes;
        Native_SCardBeginTransaction;
        Native_SCardCancel;
        Native_SCardConnect;
        Native_SCardDisconnect;
        Native_SCardEndTransaction;
        Native_SCardEstablishContext;
        Native_SCardGetStatusChange;
        Native_SCardListReaders;
        Native_SCardReconnect;
        Native_SCardReleaseContext;
        Native_SCardTransmit;
    local:
        *;
};