// Copyright 2021 Yubico AB
//
// Licensed under the Apache License, Version 2.0 (the "License").
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

namespace Yubico.YubiKey.Piv
{
    /// <summary>
    /// This enum lists the possible status values of a key in a PIV slot.
    /// </summary>
    /// <remarks>
    /// The PIN, PUK, or management key can be default, an asymmetric key can be
    /// imported or generated. If there is no key in the slot the status is
    /// Unknown.
    /// </remarks>
    public enum PivKeyStatus
    {
        /// <summary>
        /// If there is no key in a slot, its status is Unknown.
        /// </summary>
        Unknown = 0,

        /// <summary>
        /// A private key was generated by the YubiKey in the secure element.
        /// </summary>
        Generated = 1,

        /// <summary>
        /// A private key was imported from off the YubiKey.
        /// </summary>
        Imported = 2,

        /// <summary>
        /// A PIN, PUK, or management key can have the default value<br/>
        /// (PIN is "123456", PUK is "12345678", management key is
        /// 0x0102030405060708 three times).
        /// </summary>
        Default = 3,

        /// <summary>
        /// The PIN, PUK, or management key is not the default value.<br/>
        /// It is not possible to have the YubiKey report the actual value.
        /// </summary>
        NotDefault = 4
    }
}
