name: ❔Question
description: Ask a question or seek clarification about the project.
title: "[Question]: <title>"
labels: ["question"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to ask a question! We strive to respond as quickly as possible.
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true
  - type: textarea
    id: question
    attributes:
      label: What is your question?
      description: Please be as detailed as possible.
      placeholder: What do you want to know?
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Any additional context around the question.
      placeholder: Provide more background information here.
