// Copyright 2025 Yubico AB
//
// Licensed under the Apache License, Version 2.0 (the "License").
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using System;
using System.Collections.Generic;
using System.Formats.Cbor;
using System.Globalization;
using System.Security.Cryptography.X509Certificates;
using Yubico.YubiKey.Cryptography;
using Yubico.YubiKey.Fido2.Cbor;
using Yubico.YubiKey.Fido2.Cose;

namespace Yubico.YubiKey.Fido2
{
    /// <summary>
    /// Contains the data returned by the YubiKey after making a credential.
    /// </summary>
    /// <remarks>
    /// When a new credential is made, the YubiKey returns data about that
    /// credential, including attestation information. There are several elements
    /// in this data and this structure contains those elements.
    /// </remarks>
    public class MakeCredentialData
    {
        // CBOR map keys defined in CTAP 2.1 section 6.1.2 (authenticatorMakeCredential response)
        private const int KeyFormat = 1;
        private const int KeyAuthData = 2;
        private const int KeyAttestationStatement = 3;
        private const int KeyEnterpriseAttestation = 4;
        private const int KeyLargeBlob = 5;

        /// <summary>
        /// The parsed attestation object containing the format, authenticator data,
        /// and attestation statement.
        /// </summary>
        public AttestationObject AttestationObject { get; }

        /// <summary>
        /// The attestation statement format identifier.
        /// See <see cref="AttestationFormats"/> for standard format identifiers.
        /// </summary>
        public string Format { get; }

        /// <summary>
        /// The object that contains both the encoded authenticator data, which
        /// is to be used in verifying the attestation statement, and the decoded
        /// elements, including the credential itself, a public key.
        /// </summary>
        /// <remarks>
        /// Save the public key in this object and use it to verify assertions
        /// returned by calling <c>GetAssertion</c>.
        /// </remarks>
        public AuthenticatorData AuthenticatorData { get; }
        
        /// <summary>
        /// The algorithm used to create the attestation statement.
        /// Defaults to <see cref="CoseAlgorithmIdentifier.ES256"/> if not specified in the attestation object.
        /// </summary>
        public CoseAlgorithmIdentifier AttestationAlgorithm { get; private set; }

        /// <summary>
        /// The signature that is the attestation statement, which can be used to
        /// verify that the public key credential was generated by the YubiKey.
        /// This is an optional element so it can be null.
        /// </summary>
        /// <remarks>
        /// Use the public key in the zero'th element of the
        /// <see cref="AttestationCertificates"/> to verify this signature. If no
        /// attestation certificate is provided, the authenticator assumes the
        /// entity that must verify the signature will have access to the
        /// appropriate cert.
        /// <para>
        /// The data to verify is the <see cref="AuthenticatorData"/>
        /// concatenated with the client data hash (from the
        /// <see cref="MakeCredentialParameters"/>).
        /// </para>
        /// </remarks>
        public ReadOnlyMemory<byte> AttestationStatement { get; private set; }

        /// <summary>
        /// The encoded CBOR map that describes the attestation statement.
        /// </summary>
        /// <remarks>
        /// <para>
        /// The other members of this class make it easy to access the individual
        /// elements of the attestation statement and supporting structures. This
        /// property returns the raw, CBOR encoded attestation statement returned
        /// by the YubiKey. This is useful if you are implementing or interoperating
        /// with the WebAuthn data types. It is often easier to copy this field
        /// over in its encoded form rather than using the parsed properties.
        /// </para>
        /// <para>
        /// For example: the WebAuthn MakeCredential operation expects an "attestation
        /// object" be returned. This is a CBOR map containing the "fmt", "attStmt",
        /// and "authData" - the keys given in string form. The "authData" is the CBOR
        /// encoded <see cref="AuthenticatorData"/> further encoded in Base64URL. The
        /// "attStmt" is the CBOR map that contains the <see cref="AttestationAlgorithm"/>,
        /// <see cref="AttestationStatement"/>, and <see cref="AttestationCertificates" />.
        /// </para>
        /// <para>
        /// Rather than reconstructing the CBOR map, we provide it here for you, already
        /// in encoded form.
        /// </para>
        /// </remarks>
        public ReadOnlyMemory<byte> EncodedAttestationStatement { get; private set; }

        /// <summary>
        /// This array contains the certificate for the public key that can be
        /// used to verify that the attestation statement, and possibly CA
        /// certificates that chain to a root. This is an optional element so it
        /// can be null.
        /// </summary>
        /// <remarks>
        /// The first cert in this list (<c>AttestationCertificates[0]</c>) will
        /// be the certificate that contains the public key that will verify the
        /// <see cref="AttestationStatement"/>. The data to verify is the
        /// <see cref="AuthenticatorData"/> concatenated with the client data
        /// hash (from the <see cref="MakeCredentialParameters"/>).
        /// </remarks>
        public IReadOnlyList<X509Certificate2>? AttestationCertificates { get; private set; }

        /// <summary>
        /// Indicates whether an enterprise attestation was returned. This is an
        /// optional value, so if the YubiKey did not return this element, the
        /// property will be null.
        /// </summary>
        /// <remarks>
        /// If there is no enterprise attestation entry in the response (this
        /// property is null), or if there was (this property is not null) and it
        /// is <c>false</c>, then there was no enterprise attestation statement
        /// returned. If there was an entry (this property is not null) and the
        /// value is <c>true</c>, then there was an enterprise attestation
        /// statement returned.
        /// </remarks>
        public bool? EnterpriseAttestation { get; private set; }

        /// <summary>
        /// If this is not null, it is the large blob key (see section 12.3 of
        /// the CTAP2 standard). This is an optional element so it can be null.
        /// </summary>
        public ReadOnlyMemory<byte>? LargeBlobKey { get; private set; }

        /// <summary>
        /// Gets the unsigned extension outputs returned by the authenticator, if any.
        /// </summary>
        /// <remarks>
        /// This dictionary contains extension outputs that are not included in the
        /// signed authenticator data. The previewSign extension uses this to return
        /// generated key material.
        /// </remarks>
        public IReadOnlyDictionary<string, ReadOnlyMemory<byte>>? UnsignedExtensionOutputs { get; private set; }

        /// <summary>
        /// This returns the raw CBOR encoded credential data from the YubiKey, as returned by the MakeCredential operation.
        /// </summary>
        public ReadOnlyMemory<byte> RawData { get; }

        // The default constructor explicitly defined. We don't want it to be
        // used.
        private MakeCredentialData()
        {
            throw new NotImplementedException();
        }

        /// <summary>
        /// Build a new instance of <see cref="MakeCredentialData"/> based on the
        /// given CBOR encoding.
        /// </summary>
        /// <remarks>
        /// The encoding must follow the definition of
        /// <c>authenticatorMakeCredential response structure</c> in section
        /// 6.1.2 of the CTAP 2.1 standard.
        /// </remarks>
        /// <param name="cborEncoding">
        /// The credential data, encoded following the CTAP 2.1 and CBOR (RFC
        /// 8949) standards.
        /// </param>
        /// <exception cref="Ctap2DataException">
        /// The <c>cborEncoding</c> is not a valid CBOR encoding, or it is not a
        /// correct encoding for FIDO2 credential data.
        /// </exception>
        public MakeCredentialData(ReadOnlyMemory<byte> cborEncoding)
        {
            RawData = cborEncoding;
            var map = new CborMap<int>(RawData);

            try
            {
                // Build AttestationObject from a re-encoded CBOR subset containing only keys {1,2,3}.
                // The full CTAP response may contain additional keys (4-6), but AttestationObject
                // should only encode the core attestation data per WebAuthn spec.
                byte[] attestationSubset = BuildAttestationObjectSubset(map);

                // Parse attestation object with full validation
                AttestationObject = new AttestationObject(attestationSubset, parseFullDetails: true);

                // Validate EC2 key type requirement
                if (AttestationObject.AuthenticatorData.CredentialPublicKey is not CoseEcPublicKey || 
                    AttestationObject.AuthenticatorData.CredentialPublicKey.Type != CoseKeyType.Ec2)
                {
                    throw new Ctap2DataException(ExceptionMessages.Ctap2UnknownAttestationFormat);
                }

                // Backward compatibility: expose properties from AttestationObject
                Format = AttestationObject.Format;
                AuthenticatorData = AttestationObject.AuthenticatorData;
                AttestationAlgorithm = AttestationObject.AttestationAlgorithm ?? CoseAlgorithmIdentifier.ES256;
                AttestationStatement = AttestationObject.AttestationStatement ?? ReadOnlyMemory<byte>.Empty;
                EncodedAttestationStatement = AttestationObject.EncodedAttestationStatement;
                AttestationCertificates = AttestationObject.AttestationCertificates;

                if (map.Contains(KeyEnterpriseAttestation))
                {
                    EnterpriseAttestation = map.ReadBoolean(KeyEnterpriseAttestation);
                }

                if (map.Contains(KeyLargeBlob))
                {
                    LargeBlobKey = map.ReadByteString(KeyLargeBlob);
                }

                if (map.Contains(PreviewSignExtension.CtapUnsignedExtensionOutputsKey))
                {
                    var unsignedMap = map.ReadMap<string>(PreviewSignExtension.CtapUnsignedExtensionOutputsKey);
                    UnsignedExtensionOutputs = PreviewSignExtension.ParseUnsignedExtensionOutputs(unsignedMap.Encoded);
                }
            }
            catch (CborContentException cborException)
            {
                throw new Ctap2DataException(
                    string.Format(
                        CultureInfo.CurrentCulture,
                        ExceptionMessages.InvalidFido2Info),
                    cborException);
            }
        }

        /// <summary>
        /// Retrieves the previewSign generated key from the unsigned extension outputs.
        /// </summary>
        /// <remarks>
        /// <para>
        /// The previewSign extension returns generated key material in the unsigned
        /// extension outputs (CTAP response key 0x06). This method parses that data
        /// and returns a <see cref="PreviewSignGeneratedKey"/> instance containing
        /// the key handle and public key components.
        /// </para>
        /// </remarks>
        /// <returns>
        /// A <see cref="PreviewSignGeneratedKey"/> if the extension was used and returned
        /// data; otherwise, <c>null</c>.
        /// </returns>
        public PreviewSignGeneratedKey? GetPreviewSignGeneratedKey()
        {
            CoseAlgorithmIdentifier? signedAlgorithm = null;
            byte[]? signedValue = null;
            if (AuthenticatorData.Extensions is not null &&
                AuthenticatorData.Extensions.TryGetValue(Extensions.PreviewSign, out signedValue))
            {
                signedAlgorithm = PreviewSignExtension.DecodeGeneratedKeyAlgorithm(signedValue);
            }

            if (UnsignedExtensionOutputs is not null &&
                UnsignedExtensionOutputs.TryGetValue(Extensions.PreviewSign, out var unsignedValue))
            {
                return PreviewSignExtension.DecodeGeneratedKey(unsignedValue, signedAlgorithm);
            }

            if (signedValue is not null)
            {
                return PreviewSignExtension.DecodeGeneratedKey(signedValue);
            }

            return null;
        }

        /// <summary>
        /// Builds a re-encoded CBOR subset containing only keys {1: fmt, 2: authData, 3: attStmt}
        /// from the full CTAP MakeCredential response map. This ensures AttestationObject only
        /// contains the core attestation data per WebAuthn spec, excluding optional keys like
        /// enterpriseAttestation (4), largeBlobKey (5), and unsignedExtensionOutputs (6).
        /// </summary>
        private static byte[] BuildAttestationObjectSubset(CborMap<int> fullResponse)
        {
            // Validate all required keys are present
            foreach (int requiredKey in new[] { KeyFormat, KeyAuthData, KeyAttestationStatement })
            {
                if (!fullResponse.Contains(requiredKey))
                {
                    throw new Ctap2DataException(ExceptionMessages.Ctap2MissingRequiredField);
                }
            }

            // Build the subset with canonical encoding
            var writer = new CborWriter(CborConformanceMode.Ctap2Canonical, convertIndefiniteLengthEncodings: true);
            writer.WriteStartMap(3);

            // Key 1: fmt
            writer.WriteInt32(KeyFormat);
            writer.WriteTextString(fullResponse.ReadTextString(KeyFormat));

            // Key 2: authData
            writer.WriteInt32(KeyAuthData);
            writer.WriteByteString(fullResponse.ReadByteString(KeyAuthData).Span);

            // Key 3: attStmt - use the preserved encoded value
            writer.WriteInt32(KeyAttestationStatement);
            writer.WriteEncodedValue(fullResponse.ReadEncodedValue(KeyAttestationStatement).Span);

            writer.WriteEndMap();
            return writer.Encode();
        }

        /// <summary>
        /// Use the zero'th public key in the
        /// <see cref="AttestationCertificates"/> list to verify the
        /// <c>AuthenticatorData</c> and client data hash using the signature
        /// that is the <see cref="AttestationStatement"/>.
        /// </summary>
        /// <remarks>
        /// If the signature verifies, this method will return <c>true</c>, and
        /// if it does not verify, it will return <c>false</c>. If there are no
        /// certificates in the list, this method will throw an exception.
        /// </remarks>
        /// <param name="clientDataHash">
        /// The client data hash sent to the YubiKey to make the credential.
        /// </param>
        /// <returns>
        /// A boolean, <c>true</c> if the attestation statement (the signature)
        /// verifies, <c>false</c> otherwise.
        /// </returns>
        /// <exception cref="InvalidOperationException">
        /// There is no cert in the attestation certificate list.
        /// </exception>
        public bool VerifyAttestation(ReadOnlyMemory<byte> clientDataHash)
        {
            if (AttestationCertificates is null || AttestationCertificates.Count == 0)
            {
                throw new InvalidOperationException(ExceptionMessages.MissingCtap2Data);
            }

            using var digester = CryptographyProviders.Sha256Creator();
            _ = digester.TransformBlock(
                AuthenticatorData.EncodedAuthenticatorData.ToArray(), 0,
                AuthenticatorData.EncodedAuthenticatorData.Length, null, 0);
            _ = digester.TransformFinalBlock(clientDataHash.ToArray(), 0, clientDataHash.Length);

            using var ecdsaVfy = new EcdsaVerify(AttestationCertificates[0]);
            return ecdsaVfy.VerifyDigestedData(digester.Hash, AttestationStatement.ToArray());
        }
    }
}
