// Copyright 2025 Yubico AB
//
// Licensed under the Apache License, Version 2.0 (the "License").
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

namespace Yubico.YubiKit.Core.Hid;

// Keyboard Mapping for de_DE.
public sealed partial class HidCodeTranslator
{
    private static HidCodeTranslator GetDE_DE()
    {
        Dictionary<char, byte> byChar = new()
        {
            ['a'] = 0x04,
            ['A'] = 0x04 | _shift,
            ['b'] = 0x05,
            ['B'] = 0x05 | _shift,
            ['c'] = 0x06,
            ['C'] = 0x06 | _shift,
            ['d'] = 0x07,
            ['D'] = 0x07 | _shift,
            ['e'] = 0x08,
            ['E'] = 0x08 | _shift,
            ['f'] = 0x09,
            ['F'] = 0x09 | _shift,
            ['g'] = 0x0a,
            ['G'] = 0x0a | _shift,
            ['h'] = 0x0b,
            ['H'] = 0x0b | _shift,
            ['i'] = 0x0c,
            ['I'] = 0x0c | _shift,
            ['j'] = 0x0d,
            ['J'] = 0x0d | _shift,
            ['k'] = 0x0e,
            ['K'] = 0x0e | _shift,
            ['l'] = 0x0f,
            ['L'] = 0x0f | _shift,
            ['m'] = 0x10,
            ['M'] = 0x10 | _shift,
            ['n'] = 0x11,
            ['N'] = 0x11 | _shift,
            ['o'] = 0x12,
            ['O'] = 0x12 | _shift,
            ['p'] = 0x13,
            ['P'] = 0x13 | _shift,
            ['q'] = 0x14,
            ['Q'] = 0x14 | _shift,
            ['r'] = 0x15,
            ['R'] = 0x15 | _shift,
            ['s'] = 0x16,
            ['S'] = 0x16 | _shift,
            ['t'] = 0x17,
            ['T'] = 0x17 | _shift,
            ['u'] = 0x18,
            ['U'] = 0x18 | _shift,
            ['v'] = 0x19,
            ['V'] = 0x19 | _shift,
            ['w'] = 0x1a,
            ['W'] = 0x1a | _shift,
            ['x'] = 0x1b,
            ['X'] = 0x1b | _shift,
            ['z'] = 0x1c,
            ['Z'] = 0x1c | _shift,
            ['y'] = 0x1d,
            ['Y'] = 0x1d | _shift,
            ['1'] = 0x1e,
            ['!'] = 0x1e | _shift,
            ['2'] = 0x1f,
            ['"'] = 0x1f | _shift,
            ['3'] = 0x20,
            ['§'] = 0x20 | _shift,
            ['4'] = 0x21,
            ['$'] = 0x21 | _shift,
            ['5'] = 0x22,
            ['%'] = 0x22 | _shift,
            ['6'] = 0x23,
            ['&'] = 0x23 | _shift,
            ['7'] = 0x24,
            ['/'] = 0x24 | _shift,
            ['8'] = 0x25,
            ['('] = 0x25 | _shift,
            ['9'] = 0x26,
            [')'] = 0x26 | _shift,
            ['0'] = 0x27,
            ['='] = 0x27 | _shift,
            ['\n'] = 0x28,
            ['\t'] = 0x2b,
            [' '] = 0x2c,
            ['ß'] = 0x2d,
            ['?'] = 0x2d | _shift,
            ['ü'] = 0x2f,
            ['Ü'] = 0x2f | _shift,
            ['+'] = 0x30,
            ['*'] = 0x30 | _shift,
            ['#'] = 0x31,
            ['\''] = 0x31 | _shift,
            ['#'] = 0x32,
            ['\''] = 0x32 | _shift,
            ['ö'] = 0x33,
            ['Ö'] = 0x33 | _shift,
            ['ä'] = 0x34,
            ['Ä'] = 0x34 | _shift,
            [','] = 0x36,
            [';'] = 0x36 | _shift,
            ['.'] = 0x37,
            [':'] = 0x37 | _shift,
            ['-'] = 0x38,
            ['_'] = 0x38 | _shift,
            ['<'] = 0x64,
            ['>'] = 0x64 | _shift
        };
        Dictionary<byte, char> byCode = new()
        {
            [0x04] = 'a',
            [0x04 | _shift] = 'A',
            [0x05] = 'b',
            [0x05 | _shift] = 'B',
            [0x06] = 'c',
            [0x06 | _shift] = 'C',
            [0x07] = 'd',
            [0x07 | _shift] = 'D',
            [0x08] = 'e',
            [0x08 | _shift] = 'E',
            [0x09] = 'f',
            [0x09 | _shift] = 'F',
            [0x0a] = 'g',
            [0x0a | _shift] = 'G',
            [0x0b] = 'h',
            [0x0b | _shift] = 'H',
            [0x0c] = 'i',
            [0x0c | _shift] = 'I',
            [0x0d] = 'j',
            [0x0d | _shift] = 'J',
            [0x0e] = 'k',
            [0x0e | _shift] = 'K',
            [0x0f] = 'l',
            [0x0f | _shift] = 'L',
            [0x10] = 'm',
            [0x10 | _shift] = 'M',
            [0x11] = 'n',
            [0x11 | _shift] = 'N',
            [0x12] = 'o',
            [0x12 | _shift] = 'O',
            [0x13] = 'p',
            [0x13 | _shift] = 'P',
            [0x14] = 'q',
            [0x14 | _shift] = 'Q',
            [0x15] = 'r',
            [0x15 | _shift] = 'R',
            [0x16] = 's',
            [0x16 | _shift] = 'S',
            [0x17] = 't',
            [0x17 | _shift] = 'T',
            [0x18] = 'u',
            [0x18 | _shift] = 'U',
            [0x19] = 'v',
            [0x19 | _shift] = 'V',
            [0x1a] = 'w',
            [0x1a | _shift] = 'W',
            [0x1b] = 'x',
            [0x1b | _shift] = 'X',
            [0x1c] = 'z',
            [0x1c | _shift] = 'Z',
            [0x1d] = 'y',
            [0x1d | _shift] = 'Y',
            [0x1e] = '1',
            [0x1e | _shift] = '!',
            [0x1f] = '2',
            [0x1f | _shift] = '"',
            [0x20] = '3',
            [0x20 | _shift] = '§',
            [0x21] = '4',
            [0x21 | _shift] = '$',
            [0x22] = '5',
            [0x22 | _shift] = '%',
            [0x23] = '6',
            [0x23 | _shift] = '&',
            [0x24] = '7',
            [0x24 | _shift] = '/',
            [0x25] = '8',
            [0x25 | _shift] = '(',
            [0x26] = '9',
            [0x26 | _shift] = ')',
            [0x27] = '0',
            [0x27 | _shift] = '=',
            [0x28] = '\n',
            [0x2b] = '\t',
            [0x2c] = ' ',
            [0x2d] = 'ß',
            [0x2d | _shift] = '?',
            [0x2f] = 'ü',
            [0x2f | _shift] = 'Ü',
            [0x30] = '+',
            [0x30 | _shift] = '*',
            [0x31] = '#',
            [0x31 | _shift] = '\'',
            [0x32] = '#',
            [0x32 | _shift] = '\'',
            [0x33] = 'ö',
            [0x33 | _shift] = 'Ö',
            [0x34] = 'ä',
            [0x34 | _shift] = 'Ä',
            [0x36] = ',',
            [0x36 | _shift] = ';',
            [0x37] = '.',
            [0x37 | _shift] = ':',
            [0x38] = '-',
            [0x38 | _shift] = '_',
            [0x64] = '<',
            [0x64 | _shift] = '>'
        };

        return new HidCodeTranslator(byChar, byCode, KeyboardLayout.de_DE);
    }
}