// Copyright 2021 Yubico AB
//
// Licensed under the Apache License, Version 2.0 (the "License").
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

namespace Yubico.YubiKey.Otp
{
    /// <summary>
    ///     The algorithms supported by the YubiKey's challenge-response mode.
    /// </summary>
    public enum ChallengeResponseAlgorithm
    {
        /// <summary>
        ///     The default value for the enumeration.
        /// </summary>
        None = 0,

        /// <summary>
        ///     The Yubico OTP mode takes a 6 byte challenge and creates a
        ///     response using the Yubico OTP algorithm, where variable fields
        ///     generated by the device creates different responses even if the
        ///     challenge is the same.
        /// </summary>
        YubicoOtp = 1,

        /// <summary>
        ///     The HMAC-SHA1 mode creates a HMAC on a 0-64 byte (0-512 bits)
        ///     data block using a 20 byte (160 bits) fixed key. As all input
        ///     to the challenge response algorithm is static, the response is
        ///     deterministic in this mode. That is, if the same challenge is
        ///     issued repeatedly, the response will be identical each time.
        /// </summary>
        HmacSha1 = 2
    }
}
