//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Formats.Cbor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CborExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CborExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yubico.DotNetPolyfills.Resources.CborExceptionMessages", typeof(CborExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The destination is too small to hold the encoded value..
        /// </summary>
        public static string Argument_EncodeDestinationTooSmall {
            get {
                return ResourceManager.GetString("Argument_EncodeDestinationTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CBOR Conformance mode &apos;{0}&apos; does not support duplicate keys..
        /// </summary>
        public static string Cbor_ConformanceMode_ContainsDuplicateKeys {
            get {
                return ResourceManager.GetString("Cbor_ConformanceMode_ContainsDuplicateKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CBOR Conformance mode &apos;{0}&apos; does not support indefinite-length data items..
        /// </summary>
        public static string Cbor_ConformanceMode_IndefiniteLengthItemsNotSupported {
            get {
                return ResourceManager.GetString("Cbor_ConformanceMode_IndefiniteLengthItemsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CBOR Conformance mode &apos;{0}&apos; does not support simple values in the range 24-31 and must be encoded as small as possible..
        /// </summary>
        public static string Cbor_ConformanceMode_InvalidSimpleValueEncoding {
            get {
                return ResourceManager.GetString("Cbor_ConformanceMode_InvalidSimpleValueEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CBOR keys not sorted in accordance with conformance mode &apos;{0}&apos;..
        /// </summary>
        public static string Cbor_ConformanceMode_KeysNotInSortedOrder {
            get {
                return ResourceManager.GetString("Cbor_ConformanceMode_KeysNotInSortedOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CBOR Conformance mode &apos;{0}&apos; does not support non-canonical integer representations..
        /// </summary>
        public static string Cbor_ConformanceMode_NonCanonicalIntegerRepresentation {
            get {
                return ResourceManager.GetString("Cbor_ConformanceMode_NonCanonicalIntegerRepresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CBOR Conformance mode &apos;{0}&apos; does not support indefinite-length items..
        /// </summary>
        public static string Cbor_ConformanceMode_RequiresDefiniteLengthItems {
            get {
                return ResourceManager.GetString("Cbor_ConformanceMode_RequiresDefiniteLengthItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CBOR Conformance mode &apos;{0}&apos; does not support tagged values..
        /// </summary>
        public static string Cbor_ConformanceMode_TagsNotSupported {
            get {
                return ResourceManager.GetString("Cbor_ConformanceMode_TagsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in COSE key handling..
        /// </summary>
        public static string Cbor_CoseKeyError {
            get {
                return ResourceManager.GetString("Cbor_CoseKeyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not at end of the definite-length data item..
        /// </summary>
        public static string Cbor_NotAtEndOfDefiniteLengthDataItem {
            get {
                return ResourceManager.GetString("Cbor_NotAtEndOfDefiniteLengthDataItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not at end of the indefinite-length data item..
        /// </summary>
        public static string Cbor_NotAtEndOfIndefiniteLengthDataItem {
            get {
                return ResourceManager.GetString("Cbor_NotAtEndOfIndefiniteLengthDataItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot perform the requested operation, the current context is &apos;{0}&apos;..
        /// </summary>
        public static string Cbor_PopMajorTypeMismatch {
            get {
                return ResourceManager.GetString("Cbor_PopMajorTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declared definite length of CBOR data item exceeds available buffer size..
        /// </summary>
        public static string Cbor_Reader_DefiniteLengthExceedsBufferSize {
            get {
                return ResourceManager.GetString("Cbor_Reader_DefiniteLengthExceedsBufferSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid tagged bignum encoding..
        /// </summary>
        public static string Cbor_Reader_InvalidBigNumEncoding {
            get {
                return ResourceManager.GetString("Cbor_Reader_InvalidBigNumEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indefinite-length CBOR string nests an invalid data item of major type {0}..
        /// </summary>
        public static string Cbor_Reader_InvalidCbor_IndefiniteLengthStringContainsInvalidDataItem {
            get {
                return ResourceManager.GetString("Cbor_Reader_InvalidCbor_IndefiniteLengthStringContainsInvalidDataItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CBOR initial byte contains invalid integer encoding.
        /// </summary>
        public static string Cbor_Reader_InvalidCbor_InvalidIntegerEncoding {
            get {
                return ResourceManager.GetString("Cbor_Reader_InvalidCbor_InvalidIntegerEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CBOR text string payload is not valid a UTF-8 encoding..
        /// </summary>
        public static string Cbor_Reader_InvalidCbor_InvalidUtf8StringEncoding {
            get {
                return ResourceManager.GetString("Cbor_Reader_InvalidCbor_InvalidUtf8StringEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current CBOR map contains an incomplete key/value pair..
        /// </summary>
        public static string Cbor_Reader_InvalidCbor_KeyMissingValue {
            get {
                return ResourceManager.GetString("Cbor_Reader_InvalidCbor_KeyMissingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A CBOR tag should always be followed by a data item..
        /// </summary>
        public static string Cbor_Reader_InvalidCbor_TagNotFollowedByValue {
            get {
                return ResourceManager.GetString("Cbor_Reader_InvalidCbor_TagNotFollowedByValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CBOR definite-length data items contains unexpected break byte..
        /// </summary>
        public static string Cbor_Reader_InvalidCbor_UnexpectedBreakByte {
            get {
                return ResourceManager.GetString("Cbor_Reader_InvalidCbor_UnexpectedBreakByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of CBOR encoding data..
        /// </summary>
        public static string Cbor_Reader_InvalidCbor_UnexpectedEndOfBuffer {
            get {
                return ResourceManager.GetString("Cbor_Reader_InvalidCbor_UnexpectedEndOfBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid tagged RFC3339 DateTime encoding..
        /// </summary>
        public static string Cbor_Reader_InvalidDateTimeEncoding {
            get {
                return ResourceManager.GetString("Cbor_Reader_InvalidDateTimeEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid tagged decimal encoding..
        /// </summary>
        public static string Cbor_Reader_InvalidDecimalEncoding {
            get {
                return ResourceManager.GetString("Cbor_Reader_InvalidDecimalEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid tagged unix time encoding..
        /// </summary>
        public static string Cbor_Reader_InvalidUnixTimeEncoding {
            get {
                return ResourceManager.GetString("Cbor_Reader_InvalidUnixTimeEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CBOR reader is already at the root data item context..
        /// </summary>
        public static string Cbor_Reader_IsAtRootContext {
            get {
                return ResourceManager.GetString("Cbor_Reader_IsAtRootContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot perform the requested operation, the next CBOR data item is of major type &apos;{0}&apos;..
        /// </summary>
        public static string Cbor_Reader_MajorTypeMismatch {
            get {
                return ResourceManager.GetString("Cbor_Reader_MajorTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more CBOR data items to read in the current context..
        /// </summary>
        public static string Cbor_Reader_NoMoreDataItemsToRead {
            get {
                return ResourceManager.GetString("Cbor_Reader_NoMoreDataItemsToRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CBOR simple value does not encode a boolean value..
        /// </summary>
        public static string Cbor_Reader_NotABooleanEncoding {
            get {
                return ResourceManager.GetString("Cbor_Reader_NotABooleanEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data item does not encode a floating point number..
        /// </summary>
        public static string Cbor_Reader_NotAFloatEncoding {
            get {
                return ResourceManager.GetString("Cbor_Reader_NotAFloatEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CBOR simple value does not encode null..
        /// </summary>
        public static string Cbor_Reader_NotANullEncoding {
            get {
                return ResourceManager.GetString("Cbor_Reader_NotANullEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CBOR data item does not encode a simple value..
        /// </summary>
        public static string Cbor_Reader_NotASimpleValueEncoding {
            get {
                return ResourceManager.GetString("Cbor_Reader_NotASimpleValueEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CBOR string is not of indefinite length..
        /// </summary>
        public static string Cbor_Reader_NotIndefiniteLengthString {
            get {
                return ResourceManager.GetString("Cbor_Reader_NotIndefiniteLengthString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to read double-precision floating point encoding as a single-precision value..
        /// </summary>
        public static string Cbor_Reader_ReadingDoubleAsSingle {
            get {
                return ResourceManager.GetString("Cbor_Reader_ReadingDoubleAsSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reader state &apos;{0}&apos; is not at the start of a data item..
        /// </summary>
        public static string Cbor_Reader_Skip_InvalidState {
            get {
                return ResourceManager.GetString("Cbor_Reader_Skip_InvalidState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CBOR tag does not match expected value..
        /// </summary>
        public static string Cbor_Reader_TagMismatch {
            get {
                return ResourceManager.GetString("Cbor_Reader_TagMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot nest data items in indefinite-length CBOR string contexts..
        /// </summary>
        public static string Cbor_Writer_CannotNestDataItemsInIndefiniteLengthStrings {
            get {
                return ResourceManager.GetString("Cbor_Writer_CannotNestDataItemsInIndefiniteLengthStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value was either too large or too small for a Decimal..
        /// </summary>
        public static string Cbor_Writer_DecimalOverflow {
            get {
                return ResourceManager.GetString("Cbor_Writer_DecimalOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding a CBOR data item to the current context exceeds its definite length..
        /// </summary>
        public static string Cbor_Writer_DefiniteLengthExceeded {
            get {
                return ResourceManager.GetString("Cbor_Writer_DefiniteLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writer contains an incomplete CBOR document..
        /// </summary>
        public static string Cbor_Writer_IncompleteCborDocument {
            get {
                return ResourceManager.GetString("Cbor_Writer_IncompleteCborDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid UTF-8 encoding..
        /// </summary>
        public static string Cbor_Writer_InvalidUtf8String {
            get {
                return ResourceManager.GetString("Cbor_Writer_InvalidUtf8String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CBOR map incomplete; each key must be followed by a corresponding value..
        /// </summary>
        public static string Cbor_Writer_MapIncompleteKeyValuePair {
            get {
                return ResourceManager.GetString("Cbor_Writer_MapIncompleteKeyValuePair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid CBOR value encoding..
        /// </summary>
        public static string Cbor_Writer_PayloadIsNotValidCbor {
            get {
                return ResourceManager.GetString("Cbor_Writer_PayloadIsNotValidCbor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be infinite or NaN..
        /// </summary>
        public static string Cbor_Writer_ValueCannotBeInfiniteOrNaN {
            get {
                return ResourceManager.GetString("Cbor_Writer_ValueCannotBeInfiniteOrNaN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CBOR encoding is invalid..
        /// </summary>
        public static string CborContentException_DefaultMessage {
            get {
                return ResourceManager.GetString("CborContentException_DefaultMessage", resourceCulture);
            }
        }
    }
}
