//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yubico.YubiKey {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Resources.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ApplicationIdNotFound {
            get {
                return ResourceManager.GetString("ApplicationIdNotFound", resourceCulture);
            }
        }
        
        internal static string BuildExternalAuthenticatePriorToLoadInitializeUpdateResponse {
            get {
                return ResourceManager.GetString("BuildExternalAuthenticatePriorToLoadInitializeUpdateResponse", resourceCulture);
            }
        }
        
        internal static string CantSelectInterIndustry {
            get {
                return ResourceManager.GetString("CantSelectInterIndustry", resourceCulture);
            }
        }
        
        internal static string CcidNotSupported {
            get {
                return ResourceManager.GetString("CcidNotSupported", resourceCulture);
            }
        }
        
        internal static string ChecksumError {
            get {
                return ResourceManager.GetString("ChecksumError", resourceCulture);
            }
        }
        
        internal static string DecodedResponseStatusWordNotSuccess {
            get {
                return ResourceManager.GetString("DecodedResponseStatusWordNotSuccess", resourceCulture);
            }
        }
        
        internal static string HidFidoNotSupported {
            get {
                return ResourceManager.GetString("HidFidoNotSupported", resourceCulture);
            }
        }
        
        internal static string HidKeyboardNotSupported {
            get {
                return ResourceManager.GetString("HidKeyboardNotSupported", resourceCulture);
            }
        }
        
        internal static string IncorrectAesKeyLength {
            get {
                return ResourceManager.GetString("IncorrectAesKeyLength", resourceCulture);
            }
        }
        
        internal static string IncorrectTripleDesKeyLength {
            get {
                return ResourceManager.GetString("IncorrectTripleDesKeyLength", resourceCulture);
            }
        }
        
        internal static string TripleDesFailed {
            get {
                return ResourceManager.GetString("TripleDesFailed", resourceCulture);
            }
        }
        
        internal static string IncorrectRsaKeyLength {
            get {
                return ResourceManager.GetString("IncorrectRsaKeyLength", resourceCulture);
            }
        }
        
        internal static string IncorrectEccKeyLength {
            get {
                return ResourceManager.GetString("IncorrectEccKeyLength", resourceCulture);
            }
        }
        
        internal static string IncorrectDigestLength {
            get {
                return ResourceManager.GetString("IncorrectDigestLength", resourceCulture);
            }
        }
        
        internal static string UnsupportedAlgorithm {
            get {
                return ResourceManager.GetString("UnsupportedAlgorithm", resourceCulture);
            }
        }
        
        internal static string InvalidPublicKeyData {
            get {
                return ResourceManager.GetString("InvalidPublicKeyData", resourceCulture);
            }
        }
        
        internal static string InvalidPrivateKeyData {
            get {
                return ResourceManager.GetString("InvalidPrivateKeyData", resourceCulture);
            }
        }
        
        internal static string UnsupportedAttestationCert {
            get {
                return ResourceManager.GetString("UnsupportedAttestationCert", resourceCulture);
            }
        }
        
        internal static string IncorrectCardCryptogram {
            get {
                return ResourceManager.GetString("IncorrectCardCryptogram", resourceCulture);
            }
        }
        
        internal static string IncorrectCiphertextLength {
            get {
                return ResourceManager.GetString("IncorrectCiphertextLength", resourceCulture);
            }
        }
        
        internal static string InvalidChannelId {
            get {
                return ResourceManager.GetString("InvalidChannelId", resourceCulture);
            }
        }
        
        internal static string InvalidCiphertextLength {
            get {
                return ResourceManager.GetString("InvalidCiphertextLength", resourceCulture);
            }
        }
        
        internal static string InvalidOutputBuffer {
            get {
                return ResourceManager.GetString("InvalidOutputBuffer", resourceCulture);
            }
        }
        
        internal static string IncorrectDerivationLength {
            get {
                return ResourceManager.GetString("IncorrectDerivationLength", resourceCulture);
            }
        }
        
        internal static string IncorrectExternalAuthenticateData {
            get {
                return ResourceManager.GetString("IncorrectExternalAuthenticateData", resourceCulture);
            }
        }
        
        internal static string IncorrectInitializeUpdateResponseData {
            get {
                return ResourceManager.GetString("IncorrectInitializeUpdateResponseData", resourceCulture);
            }
        }
        
        internal static string IncorrectIVLength {
            get {
                return ResourceManager.GetString("IncorrectIVLength", resourceCulture);
            }
        }
        
        internal static string IncorrectPlaintextLength {
            get {
                return ResourceManager.GetString("IncorrectPlaintextLength", resourceCulture);
            }
        }
        
        internal static string IncorrectResponseLengthToDecrypt {
            get {
                return ResourceManager.GetString("IncorrectResponseLengthToDecrypt", resourceCulture);
            }
        }
        
        internal static string IncorrectRmac {
            get {
                return ResourceManager.GetString("IncorrectRmac", resourceCulture);
            }
        }
        
        internal static string IncorrectStaticKeyLength {
            get {
                return ResourceManager.GetString("IncorrectStaticKeyLength", resourceCulture);
            }
        }
        
        internal static string InsufficientResponseLengthToVerifyRmac {
            get {
                return ResourceManager.GetString("InsufficientResponseLengthToVerifyRmac", resourceCulture);
            }
        }
        
        internal static string InvalidHostChallengeLength {
            get {
                return ResourceManager.GetString("InvalidHostChallengeLength", resourceCulture);
            }
        }
        
        internal static string InvalidInitializeUpdateResponse {
            get {
                return ResourceManager.GetString("InvalidInitializeUpdateResponse", resourceCulture);
            }
        }
        
        internal static string InvalidOtpSlot {
            get {
                return ResourceManager.GetString("InvalidOtpSlot", resourceCulture);
            }
        }
        
        internal static string InvalidPadding {
            get {
                return ResourceManager.GetString("InvalidPadding", resourceCulture);
            }
        }
        
        internal static string LoadExternalAuthenticateResponsePriorToLoadInitializUpdateResponse {
            get {
                return ResourceManager.GetString("LoadExternalAuthenticateResponsePriorToLoadInitializUpdateResponse", resourceCulture);
            }
        }
        
        internal static string LoadInitializeUpdatePriorToBuild {
            get {
                return ResourceManager.GetString("LoadInitializeUpdatePriorToBuild", resourceCulture);
            }
        }
        
        internal static string ManagementApplicationUnavailable {
            get {
                return ResourceManager.GetString("ManagementApplicationUnavailable", resourceCulture);
            }
        }
        
        internal static string NoResponseDataApduFailed {
            get {
                return ResourceManager.GetString("NoResponseDataApduFailed", resourceCulture);
            }
        }
        
        internal static string InvalidApduResponseData {
            get {
                return ResourceManager.GetString("InvalidApduResponseData", resourceCulture);
            }
        }
        
        internal static string CommandResponseApduUnexpectedResult {
            get {
                return ResourceManager.GetString("CommandResponseApduUnexpectedResult", resourceCulture);
            }
        }
        
        internal static string IncompleteCommandInput {
            get {
                return ResourceManager.GetString("IncompleteCommandInput", resourceCulture);
            }
        }
        
        internal static string NoMoreRetriesRemaining {
            get {
                return ResourceManager.GetString("NoMoreRetriesRemaining", resourceCulture);
            }
        }
        
        internal static string YubiKeyNotAuthenticatedInPiv {
            get {
                return ResourceManager.GetString("YubiKeyNotAuthenticatedInPiv", resourceCulture);
            }
        }
        
        internal static string MissingKeyCollector {
            get {
                return ResourceManager.GetString("MissingKeyCollector", resourceCulture);
            }
        }
        
        internal static string StreamNotReadable {
            get {
                return ResourceManager.GetString("StreamNotReadable", resourceCulture);
            }
        }
        
        internal static string InvalidSlot {
            get {
                return ResourceManager.GetString("InvalidSlot", resourceCulture);
            }
        }
        
        internal static string InvalidAlgorithm {
            get {
                return ResourceManager.GetString("InvalidAlgorithm", resourceCulture);
            }
        }
        
        internal static string ApplicationResetFailure {
            get {
                return ResourceManager.GetString("ApplicationResetFailure", resourceCulture);
            }
        }
        
        internal static string InvalidPinPukLength {
            get {
                return ResourceManager.GetString("InvalidPinPukLength", resourceCulture);
            }
        }
        
        internal static string InvalidPivPutDataLength {
            get {
                return ResourceManager.GetString("InvalidPivPutDataLength", resourceCulture);
            }
        }
        
        internal static string InvalidPivPinOnlyMode {
            get {
                return ResourceManager.GetString("InvalidPivPinOnlyMode", resourceCulture);
            }
        }
        
        internal static string PinOnlyNotPossible {
            get {
                return ResourceManager.GetString("PinOnlyNotPossible", resourceCulture);
            }
        }
        
        internal static string MgmtKeyCannotBeChanged {
            get {
                return ResourceManager.GetString("MgmtKeyCannotBeChanged", resourceCulture);
            }
        }
        
        internal static string InvalidPinPukRetryCount {
            get {
                return ResourceManager.GetString("InvalidPinPukRetryCount", resourceCulture);
            }
        }
        
        internal static string NotSupportedByYubiKeyVersion {
            get {
                return ResourceManager.GetString("NotSupportedByYubiKeyVersion", resourceCulture);
            }
        }
        
        internal static string InvalidDataTag {
            get {
                return ResourceManager.GetString("InvalidDataTag", resourceCulture);
            }
        }
        
        internal static string InvalidDataEncoding {
            get {
                return ResourceManager.GetString("InvalidDataEncoding", resourceCulture);
            }
        }
        
        internal static string CannotUseDataTagAsAlternate {
            get {
                return ResourceManager.GetString("CannotUseDataTagAsAlternate", resourceCulture);
            }
        }
        
        internal static string NoDataToEncode {
            get {
                return ResourceManager.GetString("NoDataToEncode", resourceCulture);
            }
        }
        
        internal static string InvalidPivDataObjectLength {
            get {
                return ResourceManager.GetString("InvalidPivDataObjectLength", resourceCulture);
            }
        }
        
        internal static string InvalidPivDataObjectValue {
            get {
                return ResourceManager.GetString("InvalidPivDataObjectValue", resourceCulture);
            }
        }
        
        internal static string OperationPriorToLoadInitializeUpdate {
            get {
                return ResourceManager.GetString("OperationPriorToLoadInitializeUpdate", resourceCulture);
            }
        }
        
        internal static string OtpConfigFlagsInvalid {
            get {
                return ResourceManager.GetString("OtpConfigFlagsInvalid", resourceCulture);
            }
        }
        
        internal static string OtpExtendedFlagsInvalid {
            get {
                return ResourceManager.GetString("OtpExtendedFlagsInvalid", resourceCulture);
            }
        }
        
        internal static string OtpTicketFlagsInvalid {
            get {
                return ResourceManager.GetString("OtpTicketFlagsInvalid", resourceCulture);
            }
        }
        
        internal static string TouchRequired {
            get {
                return ResourceManager.GetString("TouchRequired", resourceCulture);
            }
        }
        
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        internal static string UnknownScp03Error {
            get {
                return ResourceManager.GetString("UnknownScp03Error", resourceCulture);
            }
        }
        
        internal static string ValueConversionFailed {
            get {
                return ResourceManager.GetString("ValueConversionFailed", resourceCulture);
            }
        }
        
        internal static string UnknownFidoError {
            get {
                return ResourceManager.GetString("UnknownFidoError", resourceCulture);
            }
        }
        
        internal static string InvalidCredential {
            get {
                return ResourceManager.GetString("InvalidCredential", resourceCulture);
            }
        }
        
        internal static string InvalidCredentialAccount {
            get {
                return ResourceManager.GetString("InvalidCredentialAccount", resourceCulture);
            }
        }
        
        internal static string InvalidCredentialNameLength {
            get {
                return ResourceManager.GetString("InvalidCredentialNameLength", resourceCulture);
            }
        }
        
        internal static string InvalidCredentialSecret {
            get {
                return ResourceManager.GetString("InvalidCredentialSecret", resourceCulture);
            }
        }
        
        internal static string InvalidCredentialDigits {
            get {
                return ResourceManager.GetString("InvalidCredentialDigits", resourceCulture);
            }
        }
        
        internal static string InvalidCredentialPeriod {
            get {
                return ResourceManager.GetString("InvalidCredentialPeriod", resourceCulture);
            }
        }
        
        internal static string ValueIsNotEnum {
            get {
                return ResourceManager.GetString("ValueIsNotEnum", resourceCulture);
            }
        }
        
        internal static string InvalidUriScheme {
            get {
                return ResourceManager.GetString("InvalidUriScheme", resourceCulture);
            }
        }
        
        internal static string InvalidUriPath {
            get {
                return ResourceManager.GetString("InvalidUriPath", resourceCulture);
            }
        }
        
        internal static string InvalidOathPassword {
            get {
                return ResourceManager.GetString("InvalidOathPassword", resourceCulture);
            }
        }
        
        internal static string InvalidChallengeLength {
            get {
                return ResourceManager.GetString("InvalidChallengeLength", resourceCulture);
            }
        }
        
        internal static string Ctap2CborIndefiniteLength {
            get {
                return ResourceManager.GetString("Ctap2CborIndefiniteLength", resourceCulture);
            }
        }
        
        internal static string Ctap2CborUnexpectedKey {
            get {
                return ResourceManager.GetString("Ctap2CborUnexpectedKey", resourceCulture);
            }
        }
        
        internal static string Ctap2CborUnexpectedValue {
            get {
                return ResourceManager.GetString("Ctap2CborUnexpectedValue", resourceCulture);
            }
        }
        
        internal static string InvalidCtap2Data {
            get {
                return ResourceManager.GetString("InvalidCtap2Data", resourceCulture);
            }
        }
        
        internal static string MissingCtap2Data {
            get {
                return ResourceManager.GetString("MissingCtap2Data", resourceCulture);
            }
        }
        
        internal static string Fido2ResponseMissing {
            get {
                return ResourceManager.GetString("Fido2ResponseMissing", resourceCulture);
            }
        }
        
        internal static string BadFido2Status {
            get {
                return ResourceManager.GetString("BadFido2Status", resourceCulture);
            }
        }
        
        internal static string NoInterfaceAvailable {
            get {
                return ResourceManager.GetString("NoInterfaceAvailable", resourceCulture);
            }
        }
        
        internal static string OtpFlagConflict {
            get {
                return ResourceManager.GetString("OtpFlagConflict", resourceCulture);
            }
        }
        
        internal static string OtpFlagRequiredOr {
            get {
                return ResourceManager.GetString("OtpFlagRequiredOr", resourceCulture);
            }
        }
        
        internal static string InvalidPropertyLength {
            get {
                return ResourceManager.GetString("InvalidPropertyLength", resourceCulture);
            }
        }
        
        internal static string PropertyValueTooLarge {
            get {
                return ResourceManager.GetString("PropertyValueTooLarge", resourceCulture);
            }
        }
        
        internal static string UnexpectedState {
            get {
                return ResourceManager.GetString("UnexpectedState", resourceCulture);
            }
        }
        
        internal static string OtpConfigFlagsNotUpdatable {
            get {
                return ResourceManager.GetString("OtpConfigFlagsNotUpdatable", resourceCulture);
            }
        }
        
        internal static string BadNdefRecordType {
            get {
                return ResourceManager.GetString("BadNdefRecordType", resourceCulture);
            }
        }
        
        internal static string MalformedNdefRecord {
            get {
                return ResourceManager.GetString("MalformedNdefRecord", resourceCulture);
            }
        }
        
        internal static string OutOfRangeUriPrefixCode {
            get {
                return ResourceManager.GetString("OutOfRangeUriPrefixCode", resourceCulture);
            }
        }
        
        internal static string WrongNdefType {
            get {
                return ResourceManager.GetString("WrongNdefType", resourceCulture);
            }
        }
        
        internal static string UnknownFido2Status {
            get {
                return ResourceManager.GetString("UnknownFido2Status", resourceCulture);
            }
        }
        
        internal static string Ctap2CommandTooLarge {
            get {
                return ResourceManager.GetString("Ctap2CommandTooLarge", resourceCulture);
            }
        }
        
        internal static string Ctap2MalformedResponse {
            get {
                return ResourceManager.GetString("Ctap2MalformedResponse", resourceCulture);
            }
        }
        
        internal static string Ctap2UnknownAttestationFormat {
            get {
                return ResourceManager.GetString("Ctap2UnknownAttestationFormat", resourceCulture);
            }
        }
        
        internal static string FailedParsingCertificate {
            get {
                return ResourceManager.GetString("FailedParsingCertificate", resourceCulture);
            }
        }
        
        internal static string InvalidOtpChallengeResponseAlgorithm {
            get {
                return ResourceManager.GetString("InvalidOtpChallengeResponseAlgorithm", resourceCulture);
            }
        }
        
        internal static string HmacChallengeTooLong {
            get {
                return ResourceManager.GetString("HmacChallengeTooLong", resourceCulture);
            }
        }
        
        internal static string YubicoOtpChallengeLengthInvalid {
            get {
                return ResourceManager.GetString("YubicoOtpChallengeLengthInvalid", resourceCulture);
            }
        }
        
        internal static string WrongHidCodeMapLength {
            get {
                return ResourceManager.GetString("WrongHidCodeMapLength", resourceCulture);
            }
        }
        
        internal static string LockCodeWrongLength {
            get {
                return ResourceManager.GetString("LockCodeWrongLength", resourceCulture);
            }
        }
        
        internal static string NdefTextTooLong {
            get {
                return ResourceManager.GetString("NdefTextTooLong", resourceCulture);
            }
        }
        
        internal static string NdefUriTooLong {
            get {
                return ResourceManager.GetString("NdefUriTooLong", resourceCulture);
            }
        }
        
        internal static string InvalidNdefConfig {
            get {
                return ResourceManager.GetString("InvalidNdefConfig", resourceCulture);
            }
        }
        
        internal static string NdefLanguageCodeTooLong {
            get {
                return ResourceManager.GetString("NdefLanguageCodeTooLong", resourceCulture);
            }
        }
        
        internal static string InvalidPin {
            get {
                return ResourceManager.GetString("InvalidPin", resourceCulture);
            }
        }
        
        internal static string InvalidPinLength {
            get {
                return ResourceManager.GetString("InvalidPinLength", resourceCulture);
            }
        }
        
        internal static string SmartCardPipelineSetupFailed {
            get {
                return ResourceManager.GetString("SmartCardPipelineSetupFailed", resourceCulture);
            }
        }
        
        internal static string InvalidCredentialType {
            get {
                return ResourceManager.GetString("InvalidCredentialType", resourceCulture);
            }
        }
        
        internal static string InvalidKeyboardInstruction {
            get {
                return ResourceManager.GetString("InvalidKeyboardInstruction", resourceCulture);
            }
        }
        
        internal static string KeyboardDataTooBig {
            get {
                return ResourceManager.GetString("KeyboardDataTooBig", resourceCulture);
            }
        }
        
        internal static string KeyboardInvalidFlag {
            get {
                return ResourceManager.GetString("KeyboardInvalidFlag", resourceCulture);
            }
        }
        
        internal static string KeyboardNoReply {
            get {
                return ResourceManager.GetString("KeyboardNoReply", resourceCulture);
            }
        }
        
        internal static string KeyboardReadReportFailed {
            get {
                return ResourceManager.GetString("KeyboardReadReportFailed", resourceCulture);
            }
        }
        
        internal static string KeyboardSequenceOutOfRange {
            get {
                return ResourceManager.GetString("KeyboardSequenceOutOfRange", resourceCulture);
            }
        }
        
        internal static string KeyboardTimeout {
            get {
                return ResourceManager.GetString("KeyboardTimeout", resourceCulture);
            }
        }
        
        internal static string KeyboardUnexpectedEndOfBuffer {
            get {
                return ResourceManager.GetString("KeyboardUnexpectedEndOfBuffer", resourceCulture);
            }
        }
        
        internal static string UserInteractionTimeout {
            get {
                return ResourceManager.GetString("UserInteractionTimeout", resourceCulture);
            }
        }
        
        internal static string InvalidDeviceNotYubico {
            get {
                return ResourceManager.GetString("InvalidDeviceNotYubico", resourceCulture);
            }
        }
        
        internal static string InvalidConnectionTypeNone {
            get {
                return ResourceManager.GetString("InvalidConnectionTypeNone", resourceCulture);
            }
        }
        
        internal static string NotImplementedHidFidoEnumeration {
            get {
                return ResourceManager.GetString("NotImplementedHidFidoEnumeration", resourceCulture);
            }
        }
        
        internal static string HidFidoWindowsNotElevated {
            get {
                return ResourceManager.GetString("HidFidoWindowsNotElevated", resourceCulture);
            }
        }
        
        internal static string InvalidDeviceNotFido {
            get {
                return ResourceManager.GetString("InvalidDeviceNotFido", resourceCulture);
            }
        }
        
        internal static string InvalidDeviceNotKeyboard {
            get {
                return ResourceManager.GetString("InvalidDeviceNotKeyboard", resourceCulture);
            }
        }
        
        internal static string InvalidStatusReport {
            get {
                return ResourceManager.GetString("InvalidStatusReport", resourceCulture);
            }
        }
        
        internal static string StatusReportNotFirstReportRead {
            get {
                return ResourceManager.GetString("StatusReportNotFirstReportRead", resourceCulture);
            }
        }
        
        internal static string ArgumentMustBeFirmwareVersion {
            get {
                return ResourceManager.GetString("ArgumentMustBeFirmwareVersion", resourceCulture);
            }
        }
        
        internal static string OtpFlagsNotValid {
            get {
                return ResourceManager.GetString("OtpFlagsNotValid", resourceCulture);
            }
        }
        
        internal static string StaticTicketNotSettable {
            get {
                return ResourceManager.GetString("StaticTicketNotSettable", resourceCulture);
            }
        }
        
        internal static string InvalidScancode {
            get {
                return ResourceManager.GetString("InvalidScancode", resourceCulture);
            }
        }
        
        internal static string UnableToVerifyOathPassword {
            get {
                return ResourceManager.GetString("UnableToVerifyOathPassword", resourceCulture);
            }
        }
        
        internal static string IncorrectOathNewPassword {
            get {
                return ResourceManager.GetString("IncorrectOathNewPassword", resourceCulture);
            }
        }
        
        internal static string OtpFlagRequired {
            get {
                return ResourceManager.GetString("OtpFlagRequired", resourceCulture);
            }
        }
        
        internal static string OtpFlagRequiredAnd {
            get {
                return ResourceManager.GetString("OtpFlagRequiredAnd", resourceCulture);
            }
        }
        
        internal static string SHA512NotSupported {
            get {
                return ResourceManager.GetString("SHA512NotSupported", resourceCulture);
            }
        }
        
        internal static string TouchNotSupported {
            get {
                return ResourceManager.GetString("TouchNotSupported", resourceCulture);
            }
        }
        
        internal static string RenameCommandNotSupported {
            get {
                return ResourceManager.GetString("RenameCommandNotSupported", resourceCulture);
            }
        }
        
        internal static string MustEnableOneAvailableUsbCapability {
            get {
                return ResourceManager.GetString("MustEnableOneAvailableUsbCapability", resourceCulture);
            }
        }
        
        internal static string AccessCodeTooLong {
            get {
                return ResourceManager.GetString("AccessCodeTooLong", resourceCulture);
            }
        }
        
        internal static string BothGenerateAndSpecify {
            get {
                return ResourceManager.GetString("BothGenerateAndSpecify", resourceCulture);
            }
        }
        
        internal static string SlotNotSet {
            get {
                return ResourceManager.GetString("SlotNotSet", resourceCulture);
            }
        }
        
        internal static string StaticPasswordInvalidLength {
            get {
                return ResourceManager.GetString("StaticPasswordInvalidLength", resourceCulture);
            }
        }
        
        internal static string LockCodeAllZeroNotAllowed {
            get {
                return ResourceManager.GetString("LockCodeAllZeroNotAllowed", resourceCulture);
            }
        }
        
        internal static string AutoEjectTimeoutRequiresTouchEjectEnabled {
            get {
                return ResourceManager.GetString("AutoEjectTimeoutRequiresTouchEjectEnabled", resourceCulture);
            }
        }
        
        internal static string SupportsOnlyUsbInterfaces {
            get {
                return ResourceManager.GetString("SupportsOnlyUsbInterfaces", resourceCulture);
            }
        }
        
        internal static string TouchEjectTimeoutRequiresCcidOnly {
            get {
                return ResourceManager.GetString("TouchEjectTimeoutRequiresCcidOnly", resourceCulture);
            }
        }
        
        internal static string MustEnableOneAvailableUsbInterface {
            get {
                return ResourceManager.GetString("MustEnableOneAvailableUsbInterface", resourceCulture);
            }
        }
        
        internal static string YubiKeyOperationFailed {
            get {
                return ResourceManager.GetString("YubiKeyOperationFailed", resourceCulture);
            }
        }
        
        internal static string OtpSwapCommandNotSupported {
            get {
                return ResourceManager.GetString("OtpSwapCommandNotSupported", resourceCulture);
            }
        }
        
        internal static string OtpSlotsNotConfigured {
            get {
                return ResourceManager.GetString("OtpSlotsNotConfigured", resourceCulture);
            }
        }
        
        internal static string BothTotpAndChallenge {
            get {
                return ResourceManager.GetString("BothTotpAndChallenge", resourceCulture);
            }
        }
        
        internal static string MustChooseTotpOrChallenge {
            get {
                return ResourceManager.GetString("MustChooseTotpOrChallenge", resourceCulture);
            }
        }
        
        internal static string OnlyOneAlgorithm {
            get {
                return ResourceManager.GetString("OnlyOneAlgorithm", resourceCulture);
            }
        }
        
        internal static string CantSpecifyPrivateIdAndGenerate {
            get {
                return ResourceManager.GetString("CantSpecifyPrivateIdAndGenerate", resourceCulture);
            }
        }
        
        internal static string CantSpecifyPublicIdAndUseSerial {
            get {
                return ResourceManager.GetString("CantSpecifyPublicIdAndUseSerial", resourceCulture);
            }
        }
        
        internal static string KeyHasNoVisibleSerial {
            get {
                return ResourceManager.GetString("KeyHasNoVisibleSerial", resourceCulture);
            }
        }
        
        internal static string MultipleExceptions {
            get {
                return ResourceManager.GetString("MultipleExceptions", resourceCulture);
            }
        }
        
        internal static string MustChooseOrGeneratePrivateId {
            get {
                return ResourceManager.GetString("MustChooseOrGeneratePrivateId", resourceCulture);
            }
        }
        
        internal static string MustChooseOrUseSerialAsPublicId {
            get {
                return ResourceManager.GetString("MustChooseOrUseSerialAsPublicId", resourceCulture);
            }
        }
        
        internal static string MustChooseOrGenerateKey {
            get {
                return ResourceManager.GetString("MustChooseOrGenerateKey", resourceCulture);
            }
        }
        
        internal static string PrivateIdWrongSize {
            get {
                return ResourceManager.GetString("PrivateIdWrongSize", resourceCulture);
            }
        }
        
        internal static string PublicIdWrongSize {
            get {
                return ResourceManager.GetString("PublicIdWrongSize", resourceCulture);
            }
        }
        
        internal static string YubicoKeyWrongSize {
            get {
                return ResourceManager.GetString("YubicoKeyWrongSize", resourceCulture);
            }
        }
        
        internal static string MustChooseAlgorithm {
            get {
                return ResourceManager.GetString("MustChooseAlgorithm", resourceCulture);
            }
        }
        
        internal static string CantSpecifyKeyAndGenerate {
            get {
                return ResourceManager.GetString("CantSpecifyKeyAndGenerate", resourceCulture);
            }
        }
        
        internal static string PrivateIdNotSet {
            get {
                return ResourceManager.GetString("PrivateIdNotSet", resourceCulture);
            }
        }
        
        internal static string PublicIdNotSet {
            get {
                return ResourceManager.GetString("PublicIdNotSet", resourceCulture);
            }
        }
        
        internal static string KeyNotSet {
            get {
                return ResourceManager.GetString("KeyNotSet", resourceCulture);
            }
        }
        
        internal static string AlgorithmNotChosen {
            get {
                return ResourceManager.GetString("AlgorithmNotChosen", resourceCulture);
            }
        }
        
        internal static string HmacKeyWrongSize {
            get {
                return ResourceManager.GetString("HmacKeyWrongSize", resourceCulture);
            }
        }
        
        internal static string IntOrCodeOnlyWithHmac {
            get {
                return ResourceManager.GetString("IntOrCodeOnlyWithHmac", resourceCulture);
            }
        }
        
        internal static string OtpCodeDigitRange {
            get {
                return ResourceManager.GetString("OtpCodeDigitRange", resourceCulture);
            }
        }
        
        internal static string YubicoOtpNotCompatible {
            get {
                return ResourceManager.GetString("YubicoOtpNotCompatible", resourceCulture);
            }
        }
        
        internal static string InvalidImfValue {
            get {
                return ResourceManager.GetString("InvalidImfValue", resourceCulture);
            }
        }
        
        internal static string RequiresNfc {
            get {
                return ResourceManager.GetString("RequiresNfc", resourceCulture);
            }
        }
        
        internal static string OtpNdefSelectFileFailed {
            get {
                return ResourceManager.GetString("OtpNdefSelectFileFailed", resourceCulture);
            }
        }
        
        internal static string CantDeleteEmptySlot {
            get {
                return ResourceManager.GetString("CantDeleteEmptySlot", resourceCulture);
            }
        }
        
        internal static string OtpNdefPropertiesHaveNoEffect {
            get {
                return ResourceManager.GetString("OtpNdefPropertiesHaveNoEffect", resourceCulture);
            }
        }
        
        internal static string OtpNdefNoTypeChosen {
            get {
                return ResourceManager.GetString("OtpNdefNoTypeChosen", resourceCulture);
            }
        }
        
        internal static string OtpNdefTypeConflict {
            get {
                return ResourceManager.GetString("OtpNdefTypeConflict", resourceCulture);
            }
        }
        
        internal static string OtpNdefInvalidLanguageCode {
            get {
                return ResourceManager.GetString("OtpNdefInvalidLanguageCode", resourceCulture);
            }
        }
        
        internal static string PasswordNotSetYet {
            get {
                return ResourceManager.GetString("PasswordNotSetYet", resourceCulture);
            }
        }
        
        internal static string MustSpecifyOrGeneratePassword {
            get {
                return ResourceManager.GetString("MustSpecifyOrGeneratePassword", resourceCulture);
            }
        }
        
        internal static string MustSpecifyKeyboardLayout {
            get {
                return ResourceManager.GetString("MustSpecifyKeyboardLayout", resourceCulture);
            }
        }
        
        internal static string MustBeSixBytesForSerial {
            get {
                return ResourceManager.GetString("MustBeSixBytesForSerial", resourceCulture);
            }
        }
        
        internal static string ValueMustBeBetweenXandY {
            get {
                return ResourceManager.GetString("ValueMustBeBetweenXandY", resourceCulture);
            }
        }
        
        internal static string DeviceDoesNotSupportApplication {
            get {
                return ResourceManager.GetString("DeviceDoesNotSupportApplication", resourceCulture);
            }
        }
        
        internal static string DeviceTypeNotRecognized {
            get {
                return ResourceManager.GetString("DeviceTypeNotRecognized", resourceCulture);
            }
        }
        
        internal static string NoActiveConnections {
            get {
                return ResourceManager.GetString("NoActiveConnections", resourceCulture);
            }
        }
        
        internal static string UnknownYubiKeyFeature {
            get {
                return ResourceManager.GetString("UnknownYubiKeyFeature", resourceCulture);
            }
        }
        
        internal static string YubiKeyNotFips {
            get {
                return ResourceManager.GetString("YubiKeyNotFips", resourceCulture);
            }
        }
        
        internal static string AlreadySet {
            get {
                return ResourceManager.GetString("AlreadySet", resourceCulture);
            }
        }
        
        internal static string InvalidU2fHidErrorCodeLength {
            get {
                return ResourceManager.GetString("InvalidU2fHidErrorCodeLength", resourceCulture);
            }
        }
        
        internal static string InvalidStatusWordMustBeNoPreciseDiagnosis {
            get {
                return ResourceManager.GetString("InvalidStatusWordMustBeNoPreciseDiagnosis", resourceCulture);
            }
        }
        
        internal static string CannotMergeDifferentParents {
            get {
                return ResourceManager.GetString("CannotMergeDifferentParents", resourceCulture);
            }
        }
        
        internal static string CborLengthMismatch {
            get {
                return ResourceManager.GetString("CborLengthMismatch", resourceCulture);
            }
        }
        
        internal static string CborWriterMustConvertIdenfiteLengths {
            get {
                return ResourceManager.GetString("CborWriterMustConvertIdenfiteLengths", resourceCulture);
            }
        }
        
        internal static string CborMapEntriesExpected {
            get {
                return ResourceManager.GetString("CborMapEntriesExpected", resourceCulture);
            }
        }
        
        internal static string CborUnexpectedMapTag {
            get {
                return ResourceManager.GetString("CborUnexpectedMapTag", resourceCulture);
            }
        }
    }
}
