//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yubico.YubiKey {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResponseStatusMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResponseStatusMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResponseStatusMessages", typeof(ResponseStatusMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication method blocked..
        /// </summary>
        internal static string BaseAuthenticationMethodBlocked {
            get {
                return ResourceManager.GetString("BaseAuthenticationMethodBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class value either not supported or invalid..
        /// </summary>
        internal static string BaseClaNotSupported {
            get {
                return ResourceManager.GetString("BaseClaNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command chaining not supported..
        /// </summary>
        internal static string BaseCommandChainingNotSupported {
            get {
                return ResourceManager.GetString("BaseCommandChainingNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command not allowed..
        /// </summary>
        internal static string BaseCommandNotAllowed {
            get {
                return ResourceManager.GetString("BaseCommandNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command not allowed (no current elementary file)..
        /// </summary>
        internal static string BaseCommandNotAllowedNoEF {
            get {
                return ResourceManager.GetString("BaseCommandNotAllowedNoEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditions of use not satisfied..
        /// </summary>
        internal static string BaseConditionsNotSatisfied {
            get {
                return ResourceManager.GetString("BaseConditionsNotSatisfied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referenced data or reference data not found..
        /// </summary>
        internal static string BaseDataNotFound {
            get {
                return ResourceManager.GetString("BaseDataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dedicated file name already exists..
        /// </summary>
        internal static string BaseDFNameAlreadyExists {
            get {
                return ResourceManager.GetString("BaseDFNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of file or record reached before reading the expected number of bytes..
        /// </summary>
        internal static string BaseEOFReached {
            get {
                return ResourceManager.GetString("BaseEOFReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, state of non-volatile memory has changed..
        /// </summary>
        internal static string BaseErrorNvmChanged {
            get {
                return ResourceManager.GetString("BaseErrorNvmChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution error..
        /// </summary>
        internal static string BaseExecutionError {
            get {
                return ResourceManager.GetString("BaseExecutionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The comand failed to complete..
        /// </summary>
        internal static string BaseFailed {
            get {
                return ResourceManager.GetString("BaseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File already exists..
        /// </summary>
        internal static string BaseFileAlreadyExists {
            get {
                return ResourceManager.GetString("BaseFileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected file deactivated..
        /// </summary>
        internal static string BaseFileDeactivated {
            get {
                return ResourceManager.GetString("BaseFileDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File or application not found..
        /// </summary>
        internal static string BaseFileOrApplicationNotFound {
            get {
                return ResourceManager.GetString("BaseFileOrApplicationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected file in termination state..
        /// </summary>
        internal static string BaseFileTerminated {
            get {
                return ResourceManager.GetString("BaseFileTerminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function error..
        /// </summary>
        internal static string BaseFunctionError {
            get {
                return ResourceManager.GetString("BaseFunctionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function not supported..
        /// </summary>
        internal static string BaseFunctionNotSupported {
            get {
                return ResourceManager.GetString("BaseFunctionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command incompatible with file structure..
        /// </summary>
        internal static string BaseIncompatibleCommand {
            get {
                return ResourceManager.GetString("BaseIncompatibleCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of sent bytes inconsistent with parameters P1-P2..
        /// </summary>
        internal static string BaseInconsistentLengthWithP1P2 {
            get {
                return ResourceManager.GetString("BaseInconsistentLengthWithP1P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of sent bytes inconsistent with TLV structure..
        /// </summary>
        internal static string BaseInconsistentLengthWithTlv {
            get {
                return ResourceManager.GetString("BaseInconsistentLengthWithTlv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect parameters P1-P2..
        /// </summary>
        internal static string BaseIncorrectP1orP2 {
            get {
                return ResourceManager.GetString("BaseIncorrectP1orP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruction value either not supported or invalid..
        /// </summary>
        internal static string BaseInsNotSupported {
            get {
                return ResourceManager.GetString("BaseInsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect parameters in the command data field..
        /// </summary>
        internal static string BaseInvalidCommandDataParameter {
            get {
                return ResourceManager.GetString("BaseInvalidCommandDataParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File control information not formatted correctly..
        /// </summary>
        internal static string BaseInvalidFileFormat {
            get {
                return ResourceManager.GetString("BaseInvalidFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameters..
        /// </summary>
        internal static string BaseInvalidParameter {
            get {
                return ResourceManager.GetString("BaseInvalidParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last command of the chain expected..
        /// </summary>
        internal static string BaseLastCommandOfChainExpected {
            get {
                return ResourceManager.GetString("BaseLastCommandOfChainExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logical channel not supported..
        /// </summary>
        internal static string BaseLogicalChannelNotSupported {
            get {
                return ResourceManager.GetString("BaseLogicalChannelNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory failure..
        /// </summary>
        internal static string BaseMemoryFailure {
            get {
                return ResourceManager.GetString("BaseMemoryFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File filled up by the last write.
        /// </summary>
        internal static string BaseNoMoreSpaceInFile {
            get {
                return ResourceManager.GetString("BaseNoMoreSpaceInFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No input data available from a sensor on the card..
        /// </summary>
        internal static string BaseNoSensorData {
            get {
                return ResourceManager.GetString("BaseNoSensorData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough memory space in the file..
        /// </summary>
        internal static string BaseNotEnoughSpace {
            get {
                return ResourceManager.GetString("BaseNotEnoughSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part of returned data may be corrupted..
        /// </summary>
        internal static string BasePartialCorruption {
            get {
                return ResourceManager.GetString("BasePartialCorruption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record not found..
        /// </summary>
        internal static string BaseRecordNotFound {
            get {
                return ResourceManager.GetString("BaseRecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference data not usable..
        /// </summary>
        internal static string BaseReferenceDataUnusable {
            get {
                return ResourceManager.GetString("BaseReferenceDataUnusable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immediate response required by the card..
        /// </summary>
        internal static string BaseResponseRequired {
            get {
                return ResourceManager.GetString("BaseResponseRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected secure messaging data objects missing..
        /// </summary>
        internal static string BaseSecureMessageDataMissing {
            get {
                return ResourceManager.GetString("BaseSecureMessageDataMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect secure messaging data objects..
        /// </summary>
        internal static string BaseSecureMessageMalformed {
            get {
                return ResourceManager.GetString("BaseSecureMessageMalformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure messaging not supported..
        /// </summary>
        internal static string BaseSecureMessagingNotSupported {
            get {
                return ResourceManager.GetString("BaseSecureMessagingNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security status not satisfied..
        /// </summary>
        internal static string BaseSecurityStatusNotSatisfied {
            get {
                return ResourceManager.GetString("BaseSecurityStatusNotSatisfied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command succeeded..
        /// </summary>
        internal static string BaseSuccess {
            get {
                return ResourceManager.GetString("BaseSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning, state of non-volatile memory has changed..
        /// </summary>
        internal static string BaseWarningNvmChanged {
            get {
                return ResourceManager.GetString("BaseWarningNvmChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning, state of non-volatile memory is unchanged..
        /// </summary>
        internal static string BaseWarningNvmUnchanged {
            get {
                return ResourceManager.GetString("BaseWarningNvmUnchanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong length..
        /// </summary>
        internal static string BaseWrongLength {
            get {
                return ResourceManager.GetString("BaseWrongLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication is not enabled..
        /// </summary>
        internal static string OathAuthNotEnabled {
            get {
                return ResourceManager.GetString("OathAuthNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic error..
        /// </summary>
        internal static string OathGenericError {
            get {
                return ResourceManager.GetString("OathGenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such object..
        /// </summary>
        internal static string OathNoSuchObject {
            get {
                return ResourceManager.GetString("OathNoSuchObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response does not match..
        /// </summary>
        internal static string OathResponseDoesNotMatch {
            get {
                return ResourceManager.GetString("OathResponseDoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication with a password is required to access the OATH application..
        /// </summary>
        internal static string OathSecurityStatusNotSatisfied {
            get {
                return ResourceManager.GetString("OathSecurityStatusNotSatisfied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong syntax..
        /// </summary>
        internal static string OathWrongSyntax {
            get {
                return ResourceManager.GetString("OathWrongSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of retries for user verification (PIN or PUK) exceeded. 0 retries remaining..
        /// </summary>
        internal static string PivPinPukBlocked {
            get {
                return ResourceManager.GetString("PivPinPukBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User verification (PIN or PUK) failed. Retries remaining: {0}..
        /// </summary>
        internal static string PivPinPukFailedWithRetries {
            get {
                return ResourceManager.GetString("PivPinPukFailedWithRetries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User verification (PIN, PUK, or Management Key) or presence (touch) requirement not satisfied..
        /// </summary>
        internal static string PivSecurityStatusNotSatisfied {
            get {
                return ResourceManager.GetString("PivSecurityStatusNotSatisfied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request was rejected due to test-of-user-presence being required..
        /// </summary>
        internal static string U2fConditionsNotSatisfied {
            get {
                return ResourceManager.GetString("U2fConditionsNotSatisfied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device is busy for the requesting channel..
        /// </summary>
        internal static string U2fHidErrorChannelBusy {
            get {
                return ResourceManager.GetString("U2fHidErrorChannelBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command in the request is invalid..
        /// </summary>
        internal static string U2fHidErrorInvalidCommand {
            get {
                return ResourceManager.GetString("U2fHidErrorInvalidCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length field is invalid for the request..
        /// </summary>
        internal static string U2fHidErrorInvalidLength {
            get {
                return ResourceManager.GetString("U2fHidErrorInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter(s) in the request is invalid..
        /// </summary>
        internal static string U2fHidErrorInvalidParameter {
            get {
                return ResourceManager.GetString("U2fHidErrorInvalidParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The packet sequence does not match the expected value..
        /// </summary>
        internal static string U2fHidErrorInvalidSequence {
            get {
                return ResourceManager.GetString("U2fHidErrorInvalidSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message has timed out..
        /// </summary>
        internal static string U2fHidErrorMessageTimeout {
            get {
                return ResourceManager.GetString("U2fHidErrorMessageTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred (U2F HID error code {0})..
        /// </summary>
        internal static string U2fHidErrorUnknown {
            get {
                return ResourceManager.GetString("U2fHidErrorUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request was rejected due to an invalid key handle..
        /// </summary>
        internal static string U2fWrongData {
            get {
                return ResourceManager.GetString("U2fWrongData", resourceCulture);
            }
        }
    }
}
