//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yubico.YubiKey {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResponseStatusMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResponseStatusMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Resources.ResponseStatusMessages", typeof(ResponseStatusMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string BaseAuthenticationMethodBlocked {
            get {
                return ResourceManager.GetString("BaseAuthenticationMethodBlocked", resourceCulture);
            }
        }
        
        internal static string BaseCommandChainingNotSupported {
            get {
                return ResourceManager.GetString("BaseCommandChainingNotSupported", resourceCulture);
            }
        }
        
        internal static string BaseCommandNotAllowed {
            get {
                return ResourceManager.GetString("BaseCommandNotAllowed", resourceCulture);
            }
        }
        
        internal static string BaseCommandNotAllowedNoEF {
            get {
                return ResourceManager.GetString("BaseCommandNotAllowedNoEF", resourceCulture);
            }
        }
        
        internal static string BaseConditionsNotSatisfied {
            get {
                return ResourceManager.GetString("BaseConditionsNotSatisfied", resourceCulture);
            }
        }
        
        internal static string BaseDataNotFound {
            get {
                return ResourceManager.GetString("BaseDataNotFound", resourceCulture);
            }
        }
        
        internal static string BaseDFNameAlreadyExists {
            get {
                return ResourceManager.GetString("BaseDFNameAlreadyExists", resourceCulture);
            }
        }
        
        internal static string BaseEOFReached {
            get {
                return ResourceManager.GetString("BaseEOFReached", resourceCulture);
            }
        }
        
        internal static string BaseErrorNvmChanged {
            get {
                return ResourceManager.GetString("BaseErrorNvmChanged", resourceCulture);
            }
        }
        
        internal static string BaseExecutionError {
            get {
                return ResourceManager.GetString("BaseExecutionError", resourceCulture);
            }
        }
        
        internal static string BaseFailed {
            get {
                return ResourceManager.GetString("BaseFailed", resourceCulture);
            }
        }
        
        internal static string BaseFileAlreadyExists {
            get {
                return ResourceManager.GetString("BaseFileAlreadyExists", resourceCulture);
            }
        }
        
        internal static string BaseFileDeactivated {
            get {
                return ResourceManager.GetString("BaseFileDeactivated", resourceCulture);
            }
        }
        
        internal static string BaseFileOrApplicationNotFound {
            get {
                return ResourceManager.GetString("BaseFileOrApplicationNotFound", resourceCulture);
            }
        }
        
        internal static string BaseFileTerminated {
            get {
                return ResourceManager.GetString("BaseFileTerminated", resourceCulture);
            }
        }
        
        internal static string BaseFunctionError {
            get {
                return ResourceManager.GetString("BaseFunctionError", resourceCulture);
            }
        }
        
        internal static string BaseFunctionNotSupported {
            get {
                return ResourceManager.GetString("BaseFunctionNotSupported", resourceCulture);
            }
        }
        
        internal static string BaseIncompatibleCommand {
            get {
                return ResourceManager.GetString("BaseIncompatibleCommand", resourceCulture);
            }
        }
        
        internal static string BaseInconsistentLengthWithP1P2 {
            get {
                return ResourceManager.GetString("BaseInconsistentLengthWithP1P2", resourceCulture);
            }
        }
        
        internal static string BaseInconsistentLengthWithTlv {
            get {
                return ResourceManager.GetString("BaseInconsistentLengthWithTlv", resourceCulture);
            }
        }
        
        internal static string BaseIncorrectP1orP2 {
            get {
                return ResourceManager.GetString("BaseIncorrectP1orP2", resourceCulture);
            }
        }
        
        internal static string BaseInvalidCommandDataParameter {
            get {
                return ResourceManager.GetString("BaseInvalidCommandDataParameter", resourceCulture);
            }
        }
        
        internal static string BaseInvalidFileFormat {
            get {
                return ResourceManager.GetString("BaseInvalidFileFormat", resourceCulture);
            }
        }
        
        internal static string BaseInvalidParameter {
            get {
                return ResourceManager.GetString("BaseInvalidParameter", resourceCulture);
            }
        }
        
        internal static string BaseLastCommandOfChainExpected {
            get {
                return ResourceManager.GetString("BaseLastCommandOfChainExpected", resourceCulture);
            }
        }
        
        internal static string BaseLogicalChannelNotSupported {
            get {
                return ResourceManager.GetString("BaseLogicalChannelNotSupported", resourceCulture);
            }
        }
        
        internal static string BaseMemoryFailure {
            get {
                return ResourceManager.GetString("BaseMemoryFailure", resourceCulture);
            }
        }
        
        internal static string BaseNoMoreSpaceInFile {
            get {
                return ResourceManager.GetString("BaseNoMoreSpaceInFile", resourceCulture);
            }
        }
        
        internal static string BaseNoSensorData {
            get {
                return ResourceManager.GetString("BaseNoSensorData", resourceCulture);
            }
        }
        
        internal static string BaseNotEnoughSpace {
            get {
                return ResourceManager.GetString("BaseNotEnoughSpace", resourceCulture);
            }
        }
        
        internal static string BasePartialCorruption {
            get {
                return ResourceManager.GetString("BasePartialCorruption", resourceCulture);
            }
        }
        
        internal static string BaseRecordNotFound {
            get {
                return ResourceManager.GetString("BaseRecordNotFound", resourceCulture);
            }
        }
        
        internal static string BaseReferenceDataUnusable {
            get {
                return ResourceManager.GetString("BaseReferenceDataUnusable", resourceCulture);
            }
        }
        
        internal static string BaseResponseRequired {
            get {
                return ResourceManager.GetString("BaseResponseRequired", resourceCulture);
            }
        }
        
        internal static string BaseSecureMessageDataMissing {
            get {
                return ResourceManager.GetString("BaseSecureMessageDataMissing", resourceCulture);
            }
        }
        
        internal static string BaseSecureMessageMalformed {
            get {
                return ResourceManager.GetString("BaseSecureMessageMalformed", resourceCulture);
            }
        }
        
        internal static string BaseSecureMessagingNotSupported {
            get {
                return ResourceManager.GetString("BaseSecureMessagingNotSupported", resourceCulture);
            }
        }
        
        internal static string BaseSecurityStatusNotSatisfied {
            get {
                return ResourceManager.GetString("BaseSecurityStatusNotSatisfied", resourceCulture);
            }
        }
        
        internal static string BaseSuccess {
            get {
                return ResourceManager.GetString("BaseSuccess", resourceCulture);
            }
        }
        
        internal static string BaseWarningNvmChanged {
            get {
                return ResourceManager.GetString("BaseWarningNvmChanged", resourceCulture);
            }
        }
        
        internal static string BaseWarningNvmUnchanged {
            get {
                return ResourceManager.GetString("BaseWarningNvmUnchanged", resourceCulture);
            }
        }
        
        internal static string OathAuthNotEnabled {
            get {
                return ResourceManager.GetString("OathAuthNotEnabled", resourceCulture);
            }
        }
        
        internal static string OathGenericError {
            get {
                return ResourceManager.GetString("OathGenericError", resourceCulture);
            }
        }
        
        internal static string OathNoSuchObject {
            get {
                return ResourceManager.GetString("OathNoSuchObject", resourceCulture);
            }
        }
        
        internal static string OathResponseDoesNotMatch {
            get {
                return ResourceManager.GetString("OathResponseDoesNotMatch", resourceCulture);
            }
        }
        
        internal static string OathWrongSyntax {
            get {
                return ResourceManager.GetString("OathWrongSyntax", resourceCulture);
            }
        }
        
        internal static string PivPinPukBlocked {
            get {
                return ResourceManager.GetString("PivPinPukBlocked", resourceCulture);
            }
        }
        
        internal static string PivPinPukFailedWithRetries {
            get {
                return ResourceManager.GetString("PivPinPukFailedWithRetries", resourceCulture);
            }
        }
        
        internal static string PivSecurityStatusNotSatisfied {
            get {
                return ResourceManager.GetString("PivSecurityStatusNotSatisfied", resourceCulture);
            }
        }
        
        internal static string OathSecurityStatusNotSatisfied {
            get {
                return ResourceManager.GetString("OathSecurityStatusNotSatisfied", resourceCulture);
            }
        }
        
        internal static string BaseClaNotSupported {
            get {
                return ResourceManager.GetString("BaseClaNotSupported", resourceCulture);
            }
        }
        
        internal static string BaseInsNotSupported {
            get {
                return ResourceManager.GetString("BaseInsNotSupported", resourceCulture);
            }
        }
        
        internal static string BaseWrongLength {
            get {
                return ResourceManager.GetString("BaseWrongLength", resourceCulture);
            }
        }
        
        internal static string Fido2NoCredentials {
            get {
                return ResourceManager.GetString("Fido2NoCredentials", resourceCulture);
            }
        }
        
        internal static string Fido2NotAllowed {
            get {
                return ResourceManager.GetString("Fido2NotAllowed", resourceCulture);
            }
        }
        
        internal static string Fido2PinNotSet {
            get {
                return ResourceManager.GetString("Fido2PinNotSet", resourceCulture);
            }
        }
        
        internal static string Fido2PinNotVerified {
            get {
                return ResourceManager.GetString("Fido2PinNotVerified", resourceCulture);
            }
        }
        
        internal static string Fido2PinBlocked {
            get {
                return ResourceManager.GetString("Fido2PinBlocked", resourceCulture);
            }
        }
        
        internal static string Fido2Timeout {
            get {
                return ResourceManager.GetString("Fido2Timeout", resourceCulture);
            }
        }
        
        internal static string Fido2ResetProcess {
            get {
                return ResourceManager.GetString("Fido2ResetProcess", resourceCulture);
            }
        }
        
        internal static string Fido2ResetTimeout {
            get {
                return ResourceManager.GetString("Fido2ResetTimeout", resourceCulture);
            }
        }
        
        internal static string Fido2AuthInvalid {
            get {
                return ResourceManager.GetString("Fido2AuthInvalid", resourceCulture);
            }
        }
        
        internal static string Fido2OperationCanceled {
            get {
                return ResourceManager.GetString("Fido2OperationCanceled", resourceCulture);
            }
        }
        
        internal static string Fido2CredentialExcluded {
            get {
                return ResourceManager.GetString("Fido2CredentialExcluded", resourceCulture);
            }
        }
        
        internal static string Fido2OptionExtension {
            get {
                return ResourceManager.GetString("Fido2OptionExtension", resourceCulture);
            }
        }
        
        internal static string U2fPinNotVerified {
            get {
                return ResourceManager.GetString("U2fPinNotVerified", resourceCulture);
            }
        }
        
        internal static string U2fConditionsNotSatisfied {
            get {
                return ResourceManager.GetString("U2fConditionsNotSatisfied", resourceCulture);
            }
        }
        
        internal static string U2fWrongData {
            get {
                return ResourceManager.GetString("U2fWrongData", resourceCulture);
            }
        }
        
        internal static string U2fHidErrorChannelBusy {
            get {
                return ResourceManager.GetString("U2fHidErrorChannelBusy", resourceCulture);
            }
        }
        
        internal static string U2fHidErrorInvalidSequence {
            get {
                return ResourceManager.GetString("U2fHidErrorInvalidSequence", resourceCulture);
            }
        }
        
        internal static string U2fHidErrorMessageTimeout {
            get {
                return ResourceManager.GetString("U2fHidErrorMessageTimeout", resourceCulture);
            }
        }
        
        internal static string U2fHidErrorUnknown {
            get {
                return ResourceManager.GetString("U2fHidErrorUnknown", resourceCulture);
            }
        }
        
        internal static string U2fHidErrorInvalidCommand {
            get {
                return ResourceManager.GetString("U2fHidErrorInvalidCommand", resourceCulture);
            }
        }
        
        internal static string U2fHidErrorInvalidLength {
            get {
                return ResourceManager.GetString("U2fHidErrorInvalidLength", resourceCulture);
            }
        }
        
        internal static string U2fHidErrorInvalidParameter {
            get {
                return ResourceManager.GetString("U2fHidErrorInvalidParameter", resourceCulture);
            }
        }
        
        internal static string YubiHsmAuthAuthenticationRequired {
            get {
                return ResourceManager.GetString("YubiHsmAuthAuthenticationRequired", resourceCulture);
            }
        }
        
        internal static string YubiHsmAuthInvalidAuthData {
            get {
                return ResourceManager.GetString("YubiHsmAuthInvalidAuthData", resourceCulture);
            }
        }
        
        internal static string YubiHsmAuthInvalidEntry {
            get {
                return ResourceManager.GetString("YubiHsmAuthInvalidEntry", resourceCulture);
            }
        }
        
        internal static string YubiHsmAuthTouchRequired {
            get {
                return ResourceManager.GetString("YubiHsmAuthTouchRequired", resourceCulture);
            }
        }
        
        internal static string YubiHsmAuthLabelConflict {
            get {
                return ResourceManager.GetString("YubiHsmAuthLabelConflict", resourceCulture);
            }
        }
    }
}
