@TestProject_HostAddress = http://localhost:5205

GET {{TestProject_HostAddress}}/di-demo/minimal
Accept: application/json

###

GET {{TestProject_HostAddress}}/di-demo/controller
Accept: application/json

###
