//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yubico.Core {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Resources.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ApduError {
            get {
                return ResourceManager.GetString("ApduError", resourceCulture);
            }
        }
        
        internal static string CmPropertyNotSupported {
            get {
                return ResourceManager.GetString("CmPropertyNotSupported", resourceCulture);
            }
        }
        
        internal static string HexNotEvenLength {
            get {
                return ResourceManager.GetString("HexNotEvenLength", resourceCulture);
            }
        }
        
        internal static string HidDriverCantAttach {
            get {
                return ResourceManager.GetString("HidDriverCantAttach", resourceCulture);
            }
        }
        
        internal static string HidUnsupportedDeviceClass {
            get {
                return ResourceManager.GetString("HidUnsupportedDeviceClass", resourceCulture);
            }
        }
        
        internal static string NfcConnectionFailed {
            get {
                return ResourceManager.GetString("NfcConnectionFailed", resourceCulture);
            }
        }
        
        internal static string ResponseApduNotEnoughBytes {
            get {
                return ResourceManager.GetString("ResponseApduNotEnoughBytes", resourceCulture);
            }
        }
        
        internal static string SCardError {
            get {
                return ResourceManager.GetString("SCardError", resourceCulture);
            }
        }
        
        internal static string LinuxUdevError {
            get {
                return ResourceManager.GetString("LinuxUdevError", resourceCulture);
            }
        }
        
        internal static string ListenRestartNotAllowed {
            get {
                return ResourceManager.GetString("ListenRestartNotAllowed", resourceCulture);
            }
        }
        
        internal static string TlvUnexpectedEndOfBuffer {
            get {
                return ResourceManager.GetString("TlvUnexpectedEndOfBuffer", resourceCulture);
            }
        }
        
        internal static string TlvUnsupportedLengthField {
            get {
                return ResourceManager.GetString("TlvUnsupportedLengthField", resourceCulture);
            }
        }
        
        internal static string TlvUnsupportedTag {
            get {
                return ResourceManager.GetString("TlvUnsupportedTag", resourceCulture);
            }
        }
        
        internal static string TlvUnexpectedEncoding {
            get {
                return ResourceManager.GetString("TlvUnexpectedEncoding", resourceCulture);
            }
        }
        
        internal static string TlvInvalidSchema {
            get {
                return ResourceManager.GetString("TlvInvalidSchema", resourceCulture);
            }
        }
        
        internal static string UnknownApduError {
            get {
                return ResourceManager.GetString("UnknownApduError", resourceCulture);
            }
        }
        
        internal static string UnknownPlatformApiError {
            get {
                return ResourceManager.GetString("UnknownPlatformApiError", resourceCulture);
            }
        }
        
        internal static string UsbInterfaceOutOfRange {
            get {
                return ResourceManager.GetString("UsbInterfaceOutOfRange", resourceCulture);
            }
        }
        
        internal static string CommandApduFieldOutOfRangeEncoding {
            get {
                return ResourceManager.GetString("CommandApduFieldOutOfRangeEncoding", resourceCulture);
            }
        }
        
        internal static string CommandApduNoValidEncoding {
            get {
                return ResourceManager.GetString("CommandApduNoValidEncoding", resourceCulture);
            }
        }
        
        internal static string CommandApduNeRangeError {
            get {
                return ResourceManager.GetString("CommandApduNeRangeError", resourceCulture);
            }
        }
        
        internal static string SCardCantEstablish {
            get {
                return ResourceManager.GetString("SCardCantEstablish", resourceCulture);
            }
        }
        
        internal static string SCardCardCantConnect {
            get {
                return ResourceManager.GetString("SCardCardCantConnect", resourceCulture);
            }
        }
        
        internal static string SCardListReadersFailed {
            get {
                return ResourceManager.GetString("SCardListReadersFailed", resourceCulture);
            }
        }
        
        internal static string SCardTransactionFailed {
            get {
                return ResourceManager.GetString("SCardTransactionFailed", resourceCulture);
            }
        }
        
        internal static string SCardTransmitFailure {
            get {
                return ResourceManager.GetString("SCardTransmitFailure", resourceCulture);
            }
        }
        
        internal static string SCardGetStatusChangeFailed {
            get {
                return ResourceManager.GetString("SCardGetStatusChangeFailed", resourceCulture);
            }
        }
        
        internal static string SCardListReadersUnexpectedLength {
            get {
                return ResourceManager.GetString("SCardListReadersUnexpectedLength", resourceCulture);
            }
        }
        
        internal static string GetUnmanagedFunctionFailed {
            get {
                return ResourceManager.GetString("GetUnmanagedFunctionFailed", resourceCulture);
            }
        }
        
        internal static string LibraryLoadFailed {
            get {
                return ResourceManager.GetString("LibraryLoadFailed", resourceCulture);
            }
        }
        
        internal static string SCardReconnectFailed {
            get {
                return ResourceManager.GetString("SCardReconnectFailed", resourceCulture);
            }
        }
        
        internal static string IOKitTypeMismatch {
            get {
                return ResourceManager.GetString("IOKitTypeMismatch", resourceCulture);
            }
        }
        
        internal static string IOKitRegistryEntryNotFound {
            get {
                return ResourceManager.GetString("IOKitRegistryEntryNotFound", resourceCulture);
            }
        }
        
        internal static string IOKitCannotOpenDevice {
            get {
                return ResourceManager.GetString("IOKitCannotOpenDevice", resourceCulture);
            }
        }
        
        internal static string IOKitOperationFailed {
            get {
                return ResourceManager.GetString("IOKitOperationFailed", resourceCulture);
            }
        }
        
        internal static string WrongIOKitRunLoopMode {
            get {
                return ResourceManager.GetString("WrongIOKitRunLoopMode", resourceCulture);
            }
        }
        
        internal static string LinuxHidOpenFailed {
            get {
                return ResourceManager.GetString("LinuxHidOpenFailed", resourceCulture);
            }
        }
        
        internal static string HidrawFailed {
            get {
                return ResourceManager.GetString("HidrawFailed", resourceCulture);
            }
        }
        
        internal static string InvalidSafeFileHandle {
            get {
                return ResourceManager.GetString("InvalidSafeFileHandle", resourceCulture);
            }
        }
        
        internal static string InvalidCharForHidCode {
            get {
                return ResourceManager.GetString("InvalidCharForHidCode", resourceCulture);
            }
        }
        
        internal static string InvalidHidCode {
            get {
                return ResourceManager.GetString("InvalidHidCode", resourceCulture);
            }
        }
        
        internal static string IllegalCharacter {
            get {
                return ResourceManager.GetString("IllegalCharacter", resourceCulture);
            }
        }
        
        internal static string InvalidBase32Digit {
            get {
                return ResourceManager.GetString("InvalidBase32Digit", resourceCulture);
            }
        }
        
        internal static string InvalidReportBufferLength {
            get {
                return ResourceManager.GetString("InvalidReportBufferLength", resourceCulture);
            }
        }
        
        internal static string EncodingOverflow {
            get {
                return ResourceManager.GetString("EncodingOverflow", resourceCulture);
            }
        }
        
        internal static string DecodingOverflow {
            get {
                return ResourceManager.GetString("DecodingOverflow", resourceCulture);
            }
        }
        
        internal static string InvalidDigit {
            get {
                return ResourceManager.GetString("InvalidDigit", resourceCulture);
            }
        }
        
        internal static string CmError {
            get {
                return ResourceManager.GetString("CmError", resourceCulture);
            }
        }
        
        internal static string EcdhKeygenFailed {
            get {
                return ResourceManager.GetString("EcdhKeygenFailed", resourceCulture);
            }
        }
        
        internal static string EcdhComputationFailed {
            get {
                return ResourceManager.GetString("EcdhComputationFailed", resourceCulture);
            }
        }
        
        internal static string InvalidAesGcmInput {
            get {
                return ResourceManager.GetString("InvalidAesGcmInput", resourceCulture);
            }
        }
        
        internal static string AesGcmFailed {
            get {
                return ResourceManager.GetString("AesGcmFailed", resourceCulture);
            }
        }
        
        internal static string InvalidCmacInput {
            get {
                return ResourceManager.GetString("InvalidCmacInput", resourceCulture);
            }
        }
        
        internal static string CmacFailed {
            get {
                return ResourceManager.GetString("CmacFailed", resourceCulture);
            }
        }
    }
}
