name: Deploy documentation

on:
  workflow_dispatch:
    inputs:
      gitops-branch:
        type: choice
        description: Environment to deploy to
        required: true
        options:
          - dev
          - stage
          - prod
      image-tag:
        type: string
        description: Image tag to deploy
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy docs
    runs-on: ubuntu-latest

    steps:
      - name: Check out current repo
        uses: actions/checkout@v4
        with:
          path: self

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.GLOBAL_GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: yubico-docs@prod-github-apps-845651.iam.gserviceaccount.com

      - name: Generate GitHub App token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: 800408 # Yubico Docs
          owner: Yubico
          repositories: docs-gitops
          private-key: ${{ secrets.GH_APP_YUBICO_DOCS_PRIVATE_KEY }}

      - name: Check out docs-gitops repo (${{ inputs.gitops-branch }} branch)
        uses: actions/checkout@v4
        with:
          repository: Yubico/docs-gitops
          ref: ${{ inputs.gitops-branch }}
          token: ${{ steps.generate_token.outputs.token }}
          path: gitops

      - name: Update GitOps resources
        run: sed -i "s#/yesdk/yesdk-docserver:.*\$#/yesdk/yesdk-docserver:$IMAGE_TAG#" ./k8s/yesdk/kustomization.yaml
        working-directory: ./gitops
        env:
          IMAGE_TAG: "${{ inputs.image-tag }}"

      - name: Set up commit signing
        run: .github/scripts/configure-git-pgp.sh
        env:
          PGP_KEY: ${{ secrets.DOCS_GITOPS_PGP_KEY }}
        working-directory: ./self

      - name: Push changes to GitOps repo
        run : ${{ github.workspace }}/self/.github/scripts/commit-and-push.sh
        working-directory: ./gitops
        env:
          DOC_PATH: docs-gitops/k8s/yesdk/kustomization.yaml
          GITOPS_BRANCH: ${{ inputs.gitops-branch }}
          IMAGE_URL: "${{ inputs.image-tag }}"

  verify:
    name: Verify deployment completion
    runs-on: ubuntu-latest
    needs: deploy

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud to read commit status
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ vars.GLOBAL_GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: github-commit-status-reader@prod-docs-403900.iam.gserviceaccount.com

    - name: Generate GitHub App token
      id: generate_token
      uses: actions/create-github-app-token@v1
      with:
        app-id: 260767 # Yubico Commit Status Reader
        owner: Yubico
        repositories: docs-gitops
        private-key: ${{ secrets.GH_APP_YUBICO_COMMIT_STATUS_READER_PRIVATE_KEY }}

    - name: Wait for deployment to complete
      run: ./.github/scripts/wait-for-commit-status.sh
      env:
        GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        ORG: yubico
        REPO: docs-gitops
        REF: ${{ inputs.gitops-branch }}
        KUSTOMIZATION_NAME: docs

    - name: Purge Fastly cache
      run: >-
        curl
        -X POST
        -H "Accept: application/json"
        -H "Fastly-Key: ${{ secrets.FASTLY_API_KEY }}"
        "https://api.fastly.com/service/${{ secrets.FASTLY_SERVICE_ID }}/purge_all"

    - name: Wait 30 seconds for Fastly cache to purge
      run: sleep 30
